### ISSUE TITLE
scATAC.fragments.txt adjusted for 9bp overhang from Tn5?

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#10]
Hi, 
I am just wondering if scATAC-pro.fragments.txt generated after mapping in the summary folder is adjusted for 9bp overhang from Tn5? If not, could you please add a module for doing so. Please see "the start of the interval is moved forward by 4bp from a left-most alignment position and backward 5bp from the right-most alignment position." - quoted from cellranger 10x fragment.tsv file. Or do you think one could use awk command to directly adjust the 9bp in scATAC-pro.fragment.txt file without errors?
Thank you so much for your help.

**Comment by wbaopaul** [comment]
Thanks for bringing this up. I guess the 9bp adjustment will not change the downstream analysis (maybe tiny change of  the overlapping qc ). I corrected it. Also, sure, you can direct change the fragments.txt file using awk.

Best,
Wenbao

**Comment by AnjaliC4** [comment]
Ok thank you very much for promptly adding the feature.
