### ISSUE TITLE
clustering step fail

### ISSUE THREAD

**Issue by henryhuang12345** [wbaopaul/scATAC-pro#13]
Hi when I run the clustering step, below is the error I kept on getting. any help? 

/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 18: 11846 Killed: 9               ${R_PATH}/Rscript --vanilla ${curr_dir}/src/clustering.R $mtx_file $CLUSTERING_METHOD $K_CLUSTERS $abs_down_dir $GENOME_NAME $TSS $norm_by $REDUCTION $nREDUCTION $Top_Variable_Features

**Comment by wbaopaul** [comment]
I guess the error may arise from high memory requirement if your data set is large. You may specify large memory for your job. BTW, which clustering method are you chosen? If it's cisTopic, I guess it requires larger memory. Or can you reproduce the error using another data? if you don't have another matrix processed by scATAC-pro, you can download one from here: https://chopri.app.box.com/s/dlqybg6agug46obiu3mhevofnq4vit4t/folder/103920591038  Thanks.

**Comment by henryhuang12345** [comment]
Hi,

I downloaded matrix.mtx alone with the configure file from the GitHub page.

I ran it the the default command line

scATAC-pro -s clustering -i matrix.mtx -c configure_user.txt

here again is the error

Wed Jun  3 04:14:12 +08 2020
Clustering ...
/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 18:  1834 Killed: 9               ${R_PATH}/Rscript --vanilla ${curr_dir}/src/clustering.R $mtx_file $CLUSTERING_METHOD $K_CLUSTERS $abs_down_dir $GENOME_NAME $TSS $norm_by $REDUCTION $nREDUCTION $Top_Variable_Features
/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 37:  1855 Killed: 9               ${R_PATH}/Rscript --vanilla ${curr_dir}/src/interface2cello.R $seurat_file ATAC
/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 30: /Users/kevinhuang/scATAC-pro/output/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 31: /Users/kevinhuang/scATAC-pro/output/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 32: /Users/kevinhuang/scATAC-pro/output/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 33: /Users/kevinhuang/scATAC-pro/output/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 34: /Users/kevinhuang/scATAC-pro/output/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/Users/kevinhuang/scatac/scATAC-pro_1.1.2/scripts/clustering.sh: line 35: /Users/kevinhuang/scATAC-pro/output/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
make[1]: *** [clustering] Error 1

**Comment by wbaopaul** [comment]
If you also downloaded features.txt and barcodes.txt files corresponding to the matrix.mtx and put them under the same folder, it's probably your system just terminate the job (maybe due to limited memory because you actually got no error for the clustering step). I just check it needs 12G memory to complete the clustering for the above PBMC data.
The other data buenrostro2018 is much smaller, you may test that instead. Hope it helps.

**Comment by henryhuang12345** [comment]
Hi is there more information for debugging, because I ran with the Buernrostro data and still got the same error. I am using a machine with 16gb of ram

**Comment by wbaopaul** [comment]
Did you change the path of the TSS file in your configure_user.txt file? Because in the clustering module, I annotated each peak (row of the matrix) using the TSS file to facilate downstream analysis. Please check the path of those annotation files. Hope this works.

**Comment by wbaopaul** [comment]
@henryhuang12345  You can also re-run the clustering step using matrix in R following this new tutorial: https://scatacpro-in-r.netlify.app/redo_downstream_in_r

**Comment by wbaopaul** [comment]
I’m closing this issue because it has been inactive for more than a month.
