### ISSUE TITLE
Several Errors 

### ISSUE THREAD

**Issue by fkeramati** [wbaopaul/scATAC-pro#16]
Hi,

I am trying for several days to get scATAC-pro work and analyze my data from 10X scATAC-seq. It gives me many many many errors! I could manage to solve several of them but still not successful in getting the analysis pipeline done successfully!!
The last error that I could not solve is related to "QC per barcode". This module writes 0 reads to barcodes.txt file and then the following steps all give error! 
For example "call cell" module afterwards says: "I have successfully read 0 cell-barcode from output/filtered_matrix/MACS2/FILTER/barcodes.txt" which does not make sense!
I am using the package on hpc with linux os.

**Comment by wbaopaul** [comment]
Please tell me more, such as how do you run it, did you check the input files for qc per barcode. Tell me as much as you can that I have a clue to help you. If your qc per barcode module got error, of course there will be many errors for other following modules.

**Comment by fkeramati** [comment]
Could you please give me your email address then I can send you the log file I got from the pipeline?

Thanks

**Comment by wbaopaul** [comment]
@fkeramati   yuw1@email.chop.edu

**Comment by wbaopaul** [comment]
Hi @fkeramati , is above issue solved? please let me know if you have any issue related. Thanks.

**Comment by fkeramati** [comment]
Hi,

Yes, I could resolve the problem with lowering the thresholds for cell identity.

Thanks
