### ISSUE TITLE
Problem with Cell calling step

### ISSUE THREAD

**Issue by JihedC** [wbaopaul/scATAC-pro#18]
Hi @wbaopaul ,

I have got an issue with the cell calling step. My log files shows this error : 

```
Run scATAC-pro 1.1.2
--------------------------------------------
Mon Jun 22 12:57:21 CEST 2020
Calling cell ...
FILTER is used for cell calling...
NULL
```

So I look at the input files required for this step and they seems to be fine. 
```
call_cell: perform cell calling
                           input: raw peak-by-barcode matrix file, outputted from the get_mtx module
                           output: filtered peak-by-cell matrix in Market Matrix format, barcodes and features,
                                   saved in output/filtered_matrix/PEAK_CALLER/CELL_CALLER/
```

the `get_mtx_module` output looks like this and I think it's okay:
```
5-A-SHARK_hg_bioinf 1.1K Jun 23 15:00 barcodes.txt
5-A-SHARK_hg_bioinf 2.0M Jun 23 15:00 features.txt
5-A-SHARK_hg_bioinf 7.8M Jun 23 15:00 matrix.mtx
```
and the fragment files contain now a column with the barcodes so I assume it works, but it seems that the cell calling is not working.

I have tried to use Cell ranger and EmptyDrop instead but I get the following error message for Cell Ranger:
```
Run scATAC-pro 1.1.2
--------------------------------------------
Wed Jun 24 12:09:48 CEST 2020
Calling cell ...
cellranger is used for cell calling...

R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(data.table)
> library(Matrix)
> library(flexmix)
Loading required package: lattice
> library(countreg)  ##install.packages("countreg", repos="http://R-Forge.R-project.org")
Error in library(countreg) : there is no package called 'countreg'
Execution halted
make: *** [/usr/local/bin/scATAC-pro_1.1.2/scripts/Makefile:163: call_cell] Error 1
Run scATAC-pro 1.1.2
```
and for EmptyDrop 
```
Run scATAC-pro 1.1.2
--------------------------------------------
Wed Jun 24 12:11:49 CEST 2020
Calling cell ...
EmptyDrop is used for cell calling...

R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> if(!require("DropletUtils")) BiocManager::install('DropletUtils')
Loading required package: DropletUtils
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.2 (2019-12-12)
Installing package(s) 'DropletUtils'
Warning in install.packages(...) :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages(...) : unable to install packages
Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> <Anonymous> -> .inet_error
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'DropletUtils'
Execution halted
make: *** [/usr/local/bin/scATAC-pro_1.1.2/scripts/Makefile:163: call_cell] Error 1
Run scATAC-pro 1.1.2
```
So it seems there are so module missing in singularity.
I am sorry for all those messages but I really hope to make this pipeline work. I hope you can help me.

Best wishes,

Jihed

**Comment by wbaopaul** [comment]
@JihedC It seems the output files of get_mtx are too small. Can you check how many rows of the barcodes.txt and how many rows for the fragment.txt file? In my case, the raw barcodes.txt file is as large as few Mb.  I guess something is wrong before call cell step and probably the fragments.txt file is too small. I will lookinto the missing packages of the singularity version. Thanks.

**Comment by JihedC** [comment]
I think that indeed there is a problem with the number of barcodes. Here are the numbers.
```
wc -l barcodes.txt
116 barcodes.txt
```


```
wc -l ATAC2.fragments.txt 
66860343 ATAC2.fragments.txt
```

I have sequenced more than 5000 cells for this sample, the 10X reports shows that they are almost all of good quality.

**Comment by wbaopaul** [comment]
right. For pbmc data, at least there are 200k barcodes outputted from get_mtx and 140m fragments after mapping in my case. Hopefully will become normal after you increase memory.

**Comment by JihedC** [comment]
But what could be the reason I get such a low amount of barcodes with my own sample?

**Comment by wbaopaul** [comment]
Oh, I thought this is about 10x pbmc data. You may check results in previous steps such as mapping qc, peaks (like do you have too limited number of peaks) to rule out if there is anything relate to bad data quality.

**Comment by JihedC** [comment]
I think the mapping was okay, here is the log file of the mapping :
```
Total_Pairs    81765563
Total_Pairs_Mapped    80139147
Total_Uniq_Mapped    71152455
Total_Mito_Mapped    1115519
Total_Dups    14786658
Total_Pairs_MAPQ30    68577892
Total_Mito_MAPQ30    845492
Total_Dups_MAPQ30    11024499
```

Most of the reads mapped to the mouse genome. Concerning the peak calling with MACS2, I get this: 

```
wc -l ATAC2_peaks.narrowPeak
189783 ATAC2_peaks.narrowPeak
``` 
To me it sound like a decent amount of peak but I am not so specialist of scATAC peaks.

The problem seems to be coming later on with the ATAC2.MACS2.qc_per_barcode.txt, which contains only 118 lines just like the barcodes.txt file from earlier.

I really don't understand where the problem might come from

**Comment by wbaopaul** [comment]
It seems normal size of peak file. How many rows for ATAC2_features_BlacklistRemoved.bed, which was used ultimately?

**Comment by JihedC** [comment]
Here it is: 

189675 ATAC2_features_BlacklistRemoved.bed

**Comment by wbaopaul** [comment]
can you check how many unique barcodes in the fragment.txt file?

**Comment by JihedC** [comment]
Hi sorry for the late reply I didn't manage to find out how to do this. The best I could get is this:

```
12978 AAAAGGCG
   2398 AAACAGCG
  14158 AAACCGCG
   1203 AAACGACG
   9019 AAACGCCG
   8008 AAACGGAG
   9223 AAACGGCA
  19979 AAACGGCC
8229056 AAACGGCG
   2156 AAACGGCT
   6202 AAACGGGG
   4603 AAACGGTG
   4586 AAACGTCG
      1 AAACNGCG
   4520 AAACTGCG
    610 AAAGGGCG
     81 AAANGGCG
   5365 AAATGGCG
  15470 AACCGGCG
   1676 AAGCGGCG
     21 AANCGGCG
   2146 AATCGGCG
   5182 ACACGGCG
  17996 ACTACCAT
   1011 AGACGGCG
   6899 AGCGTTTC
   1030 ANACGGCG
   1834 ATACGGCG
  23834 ATGTAAGA
   2015 CAACGGCG
  12226 CATACCAT
  45143 CCAACCAT
   3387 CCCACCAT
  12324 CCGACCAT
     51 CCNACCAT
  12194 CCTAACAT
  25525 CCTACAAT
  69266 CCTACCAA
   3141 CCTACCAC
  12325 CCTACCAG
18983082 CCTACCAT
  25170 CCTACCCT
   4286 CCTACCGT
   6571 CCTACCTT
   6975 CCTACGAT
   9023 CCTACTAT
   3531 CCTAGCAT
      4 CCTANCAT
   7904 CCTATCAT
  31819 CCTCCCAT
   4681 CCTGCCAT
```

There seems to be a lot of repetition of the same barcode no?

**Comment by wbaopaul** [comment]
you can use shell command `cut -f4 ATAC2.fragments.txt | uniq -u | wc -l` to check the number of unique barcodes in the fragment file.

**Comment by JihedC** [comment]
Thanks here is the output :

38066745

**Comment by wbaopaul** [comment]
sorry, it's `cut -f4 ATAC2.fragments.txt | sort -u | wc -l`. In the *get_mtx* module, I only filter out barcodes with less than 5 unique fragments. Don't understand why only around 100 barcode left. If possible, can you share me the fragment file through email: yuw1@email.chop.edu.

**Comment by JihedC** [comment]
Now the output is only 120.
The `ATAC2.fragments.txt` is around 2.2G, I will try to send it to you.

**Comment by wbaopaul** [comment]
Then you don't need to send me the file; that means you only have 120 cell barcodes in the data. That's too wierd. Did you use 10x platform for the experiment?  If so, tell me how do you run the *process* or the demultiplex module.

**Comment by JihedC** [comment]
Hi,

Yes my data is from 10X.

I went back to the beginning of the script and I think I spotted a mistake:

```

# Create a bulk fastq  file for ATAC2 (WT) as input of scatacpro

cat ATAC_2_S1_L001_R1_001.fastq.gz ATAC_2_S1_L002_R1_001.fastq.gz ATAC_2_S1_L003_R1_001.fastq.gz ATAC_2_S1_L004_R1_001.fastq.gz > ATAC2.R1.fastq.gz


cat ATAC_2_S1_L001_R3_001.fastq.gz ATAC_2_S1_L002_R3_001.fastq.gz ATAC_2_S1_L003_R3_001.fastq.gz ATAC_2_S1_L004_R3_001.fastq.gz > ATAC2.R2.fastq.gz


cat ATAC_2_S1_L001_I1_001.fastq.gz ATAC_2_S1_L002_I1_001.fastq.gz ATAC_2_S1_L003_I1_001.fastq.gz ATAC_2_S1_L004_I1_001.fastq.gz > index.fastq.gz

```

This is what I did to create the bulk ATAC-seq data, I think the mistake was on the 3rd line of the script, I used I1 instead of R2. Can you confirm?

**Comment by wbaopaul** [comment]
right. R2 is the index fast files.

**Comment by JihedC** [comment]
Hi Thanks for your help, now that I figured the last problem it the `cell-call` function works but I have got another problem later on with the `clustering`.
It seems that the `mclust` package is missing from singularity, here is the log file I got:
```
Run scATAC-pro 1.1.4
--------------------------------------------
Tue Jul 21 12:15:21 CEST 2020
Clustering ...
Registered S3 method overwritten by 'R.oo':
  method        from
  throw.default R.methodsS3

No methods found in package 'IRanges' for request: 'score' when loading 'TFBSTools'
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
    tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: 'S4Vectors'

The following objects are masked from 'package:data.table':

    first, second

The following object is masked from 'package:base':

    expand.grid

Loading required package: IRanges

Attaching package: 'IRanges'

The following object is masked from 'package:data.table':

    shift

Loading required package: GenomeInfoDb
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: 'matrixStats'

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians

Loading required package: BiocParallel

Attaching package: 'DelayedArray'

The following objects are masked from 'package:matrixStats':

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from 'package:base':

    aperm, apply, rowsum


Attaching package: 'SummarizedExperiment'

The following object is masked from 'package:Seurat':

    Assays

Loading required package: limma

Attaching package: 'limma'

The following object is masked from 'package:BiocGenerics':

    plotMA


Attaching package: 'edgeR'

The following object is masked from 'package:chromVAR':

    getCounts

Error in library(mclust) : there is no package called 'mclust'
Calls: source_local -> source -> withVisible -> eval -> eval -> library
Execution halted
Registered S3 method overwritten by 'R.oo':
  method        from
  throw.default R.methodsS3

No methods found in package 'IRanges' for request: 'score' when loading 'TFBSTools'
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs


The following objects are masked from 'package:base':

    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
    tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: 'S4Vectors'

The following objects are masked from 'package:data.table':

    first, second

The following object is masked from 'package:base':

    expand.grid

Loading required package: IRanges

Attaching package: 'IRanges'

The following object is masked from 'package:data.table':

    shift

Loading required package: GenomeInfoDb
Loading required package: Biobase
Welcome to Bioconductor

Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: 'matrixStats'

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians

Loading required package: BiocParallel

Attaching package: 'DelayedArray'

The following objects are masked from 'package:matrixStats':

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from 'package:base':

    aperm, apply, rowsum


Attaching package: 'SummarizedExperiment'

The following object is masked from 'package:Seurat':

    Assays

Loading required package: limma

Attaching package: 'limma'

The following object is masked from 'package:BiocGenerics':

    plotMA


Attaching package: 'edgeR'

The following object is masked from 'package:chromVAR':

    getCounts

Error in library(mclust) : there is no package called 'mclust'
Calls: source_local -> source -> withVisible -> eval -> eval -> library
Execution halted
/usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 30: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 31: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 32: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 33: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 34: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 35: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
make: *** [/usr/local/bin/scATAC-pro_1.1.4/scripts/Makefile:203: clustering] Error 1

```

Can you check singularity?

**Comment by wbaopaul** [comment]
The missed packages for singularity version have been installed and please download and install it again. Thanks.

**Comment by JihedC** [comment]
Thanks a lot for your quick response!

**Comment by JihedC** [comment]
That solved the issue ! Thanks!

**Comment by sebboegel** [comment]
> Hi Thanks for your help, now that I figured the last problem it the `cell-call` function works but I have got another problem later on with the `clustering`.
> It seems that the `mclust` package is missing from singularity, here is the log file I got:
> 
> ```
> Run scATAC-pro 1.1.4
> --------------------------------------------
> Tue Jul 21 12:15:21 CEST 2020
> Clustering ...
> Registered S3 method overwritten by 'R.oo':
>   method        from
>   throw.default R.methodsS3
> 
> No methods found in package 'IRanges' for request: 'score' when loading 'TFBSTools'
> Loading required package: GenomicRanges
> Loading required package: stats4
> Loading required package: BiocGenerics
> Loading required package: parallel
> 
> Attaching package: 'BiocGenerics'
> 
> The following objects are masked from 'package:parallel':
> 
>     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
>     clusterExport, clusterMap, parApply, parCapply, parLapply,
>     parLapplyLB, parRapply, parSapply, parSapplyLB
> 
> The following objects are masked from 'package:stats':
> 
>     IQR, mad, sd, var, xtabs
> 
> The following objects are masked from 'package:base':
> 
>     Filter, Find, Map, Position, Reduce, anyDuplicated, append,
>     as.data.frame, basename, cbind, colnames, dirname, do.call,
>     duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
>     lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
>     pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
>     tapply, union, unique, unsplit, which, which.max, which.min
> 
> Loading required package: S4Vectors
> 
> Attaching package: 'S4Vectors'
> 
> The following objects are masked from 'package:data.table':
> 
>     first, second
> 
> The following object is masked from 'package:base':
> 
>     expand.grid
> 
> Loading required package: IRanges
> 
> Attaching package: 'IRanges'
> 
> The following object is masked from 'package:data.table':
> 
>     shift
> 
> Loading required package: GenomeInfoDb
> Loading required package: Biobase
> Welcome to Bioconductor
> 
>     Vignettes contain introductory material; view with
>     'browseVignettes()'. To cite Bioconductor, see
>     'citation("Biobase")', and for packages 'citation("pkgname")'.
> 
> Loading required package: DelayedArray
> Loading required package: matrixStats
> 
> Attaching package: 'matrixStats'
> 
> The following objects are masked from 'package:Biobase':
> 
>     anyMissing, rowMedians
> 
> Loading required package: BiocParallel
> 
> Attaching package: 'DelayedArray'
> 
> The following objects are masked from 'package:matrixStats':
> 
>     colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges
> 
> The following objects are masked from 'package:base':
> 
>     aperm, apply, rowsum
> 
> 
> Attaching package: 'SummarizedExperiment'
> 
> The following object is masked from 'package:Seurat':
> 
>     Assays
> 
> Loading required package: limma
> 
> Attaching package: 'limma'
> 
> The following object is masked from 'package:BiocGenerics':
> 
>     plotMA
> 
> 
> Attaching package: 'edgeR'
> 
> The following object is masked from 'package:chromVAR':
> 
>     getCounts
> 
> Error in library(mclust) : there is no package called 'mclust'
> Calls: source_local -> source -> withVisible -> eval -> eval -> library
> Execution halted
> Registered S3 method overwritten by 'R.oo':
>   method        from
>   throw.default R.methodsS3
> 
> No methods found in package 'IRanges' for request: 'score' when loading 'TFBSTools'
> Loading required package: GenomicRanges
> Loading required package: stats4
> Loading required package: BiocGenerics
> Loading required package: parallel
> 
> Attaching package: 'BiocGenerics'
> 
> The following objects are masked from 'package:parallel':
> 
>     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
>     clusterExport, clusterMap, parApply, parCapply, parLapply,
>     parLapplyLB, parRapply, parSapply, parSapplyLB
> 
> The following objects are masked from 'package:stats':
> 
>     IQR, mad, sd, var, xtabs
> 
> 
> The following objects are masked from 'package:base':
> 
>     Filter, Find, Map, Position, Reduce, anyDuplicated, append,
>     as.data.frame, basename, cbind, colnames, dirname, do.call,
>     duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
>     lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
>     pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
>     tapply, union, unique, unsplit, which, which.max, which.min
> 
> Loading required package: S4Vectors
> 
> Attaching package: 'S4Vectors'
> 
> The following objects are masked from 'package:data.table':
> 
>     first, second
> 
> The following object is masked from 'package:base':
> 
>     expand.grid
> 
> Loading required package: IRanges
> 
> Attaching package: 'IRanges'
> 
> The following object is masked from 'package:data.table':
> 
>     shift
> 
> Loading required package: GenomeInfoDb
> Loading required package: Biobase
> Welcome to Bioconductor
> 
> Vignettes contain introductory material; view with
>     'browseVignettes()'. To cite Bioconductor, see
>     'citation("Biobase")', and for packages 'citation("pkgname")'.
> 
> Loading required package: DelayedArray
> Loading required package: matrixStats
> 
> Attaching package: 'matrixStats'
> 
> The following objects are masked from 'package:Biobase':
> 
>     anyMissing, rowMedians
> 
> Loading required package: BiocParallel
> 
> Attaching package: 'DelayedArray'
> 
> The following objects are masked from 'package:matrixStats':
> 
>     colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges
> 
> The following objects are masked from 'package:base':
> 
>     aperm, apply, rowsum
> 
> 
> Attaching package: 'SummarizedExperiment'
> 
> The following object is masked from 'package:Seurat':
> 
>     Assays
> 
> Loading required package: limma
> 
> Attaching package: 'limma'
> 
> The following object is masked from 'package:BiocGenerics':
> 
>     plotMA
> 
> 
> Attaching package: 'edgeR'
> 
> The following object is masked from 'package:chromVAR':
> 
>     getCounts
> 
> Error in library(mclust) : there is no package called 'mclust'
> Calls: source_local -> source -> withVisible -> eval -> eval -> library
> Execution halted
> /usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 30: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
> /usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 31: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
> /usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 32: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
> /usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 33: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
> /usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 34: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
> /usr/local/bin/scATAC-pro_1.1.4/scripts/clustering.sh: line 35: /exports/humgen/jihed/scatacpro/output/downstream_analysis/MACS2/cellranger/VisCello_obj/config.yml: No such file or directory
> make: *** [/usr/local/bin/scATAC-pro_1.1.4/scripts/Makefile:203: clustering] Error 1
> ```
> 
> Can you check singularity?

@JihedC How did you solve the issue with the cell calling?
