### ISSUE TITLE
Mapping step error 

### ISSUE THREAD

**Issue by sidrahmaryam** [wbaopaul/scATAC-pro#19]
Hey,
I am performing the given protocol. While on the mapping step, I got the following error. :

---
---
BWA Mapping Done!
convert to bam ...
Converting sam to bam ...
Sorting bam file
[**bam_sort_core] merging from 0 files and 111 in-memory blocks...
Error creating thread pool
make: *** [/storage/gaurav.ahuja/sidrah/work/scATAC-pro/scripts/Makefile:67: mapping] Error 1**

Please suggest a solution for it. 
Thanks

**Comment by wbaopaul** [comment]
I am not sure, maybe due to lack of memory. please provide more information relate to like how did you run it, what's the your configure file setting and you can also check the intermediate results in output/mapping_results/ see anything abnormal.

**Comment by wbaopaul** [comment]
Hi @sidrahmaryam , is your above issue solved? Let me know if you have any issue relate to this. Thanks.

**Comment by sidrahmaryam** [comment]
Yes it got resolved. There was some memory issue, as the file was big. Thank you. 
You can surely close this issue.
