### ISSUE TITLE
Annotation for mm10

### ISSUE THREAD

**Issue by jonasungerback** [wbaopaul/scATAC-pro#2]
Hello again,

would it be possible for you to provide similar annotation files as you have for hg38 for mm10 or provide an explaination how the hg38 was derived so I can try to replicate it for mm10?

Once again, thank you!

Jonas

**Comment by wbaopaul** [comment]
The annotation files for mm10 were just uploaded. Thanks.

Wenbao

**Comment by jonasungerback** [comment]
Many thanks!

**Comment by jambocurious** [comment]
Hi! Do you have also by accident hg19 annotations? How you define enhancer list? 
Thanks

**Comment by wbaopaul** [comment]
I also uploaded hg19 annotations. Those list was curated by cellranger-atac.
