### ISSUE TITLE
nproc: command not found make[1]: *** [process] Error 127

### ISSUE THREAD

**Issue by sylestiel** [wbaopaul/scATAC-pro#21]
/usr/local/bin/scATAC-pro_1.1.4/scripts/trimming.sh: line 20: nproc: command not found
make[1]: *** [process] Error 127

**Comment by wbaopaul** [comment]
nproc is not supportted by mac; I guess there are many other commands not support by mac OS. I will try to adjust those commands compatible for mac OS but may not have enough time to adjust all in a short time. Please switch to a linux server or HPC or using docker or singularity version. Generally, it's not recommend to run scatac-pro on mac pc; there are many module (like the mapping module) requires very large memory, so I geuss it's not realistic to run it on mac pc anyway.

**Comment by wbaopaul** [comment]
For this specific issue, you can add run `alias nproc="sysctl -n hw.logicalcpu"` in your terminal before you run scatac-pro on your mac.

**Comment by sylestiel** [comment]
Thank you. Looking forward to a mac compatible command line.
