### ISSUE TITLE
Motif analysis in downstream

### ISSUE THREAD

**Issue by sidrahmaryam** [wbaopaul/scATAC-pro#22]
Hello, 
I was trying to replicate the paper on the given dataset. In TF motif enrichment analysis step of downstream, I got this error:

**chromVar.obj = readRDS(paste0(down_dir, '/chromVar_obj.rds'))
Error in if (len > 1) paste(len, " elements, ", sep = "") else "" : 
  argument is of length zero**

while the files i took were from the shared folder here. [https://chopri.app.box.com/s/cuf17lojtuvqcvfp3kujlranbbt8x6j9](url)

Please help

**Comment by wbaopaul** [comment]
Seems you cannot read the chromVar result. Which chromVAR version and R version are you using? I have tested the tutorial codes under R/3.6.2 with chromVAR v1.0.8.

**Comment by sidrahmaryam** [comment]
Thank you for the response. I am using R/3.6.1 and chromVar v1.5.

**Comment by wbaopaul** [comment]
I never used  any chromVar version as old as v1.5. Please try to update it to v1.8.

**Comment by sidrahmaryam** [comment]
Okay. Thanks. Will try that.

**Comment by sidrahmaryam** [comment]
Thank you. It did work by updating the version.

I needed one more help please. In case we only need to run downstream on our data, then what files would be only needed? As in that folder given through link, there are various file which were obtained in previous steps. So on a fresh data, without performing the previous steps, how to just do the downstream? Please guide. 

Please tell.

**Comment by sidrahmaryam** [comment]
> I never used any chromVar version as old as v1.5. Please try to update it to v1.8.

Done!! And it worked, Thank you.

**Comment by wbaopaul** [comment]
Since this issue was solved, I am going to close it.
