### ISSUE TITLE
Downstream analysis

### ISSUE THREAD

**Issue by sidrahmaryam** [wbaopaul/scATAC-pro#23]
i needed one help please. In case we only need to run downstream on our data, then what files would be only needed? As in that folder given through link, there are various file which were obtained in previous steps. So on a fresh data, without performing the previous steps, how to just do the downstream? Please tell. 
Or is it mandatory to run the steps first before downstreaming.?

**Comment by wbaopaul** [comment]
If you have the filtered matrix, you can run most downstream analysis. You can check the formats of files in my shared pbmc10x output folder filtered_matrix/, and there are three files required: the features.txt (which is the peak), the barcodes.txt, and the corresponding peak-by-cell sparse matrix (in MatrixMarket format). The features.txt and barcodes.txt are the rownames and colnames of the matrix.mtx file. You can `read_mtx_scATACpro` function in scATAC-pro to read the matrix.

**Comment by sidrahmaryam** [comment]
Okay. Thanks a lot for helping. I am a newbie in this area, so facing quite a few issues.

**Comment by sidrahmaryam** [comment]
Hello, but the files required for DA are majorly mapping stats and fragment files as it most operations are done on it. I have the peak, barcodes and the matrix file. peak file is not being used anywhere, but the fragment and the mapping file. Can you please suggest me the solution.

**Comment by sidrahmaryam** [comment]
I need to do :
GO motif analysis, TF footprinting, TF motif enrichment analysis, Cicero cis-interaction.

**Comment by wbaopaul** [comment]
Please check the github tutorial for the input for each module. For short, you need to run `clustering `module.  It generates a seurat object and clustering result which will be used by some downstrame analysis. Besides, bam file is required for TF footprinting analysis. I recommend running the processing modules as well otherwise more time may needed for troubleshooting.

**Comment by sidrahmaryam** [comment]
Okay, so basically I have to run some of the steps explained before for a successful downstream.
Thanks a lot for the help.

**Comment by wbaopaul** [comment]
I will close this issue since no updates for more than 2 monthes.
