### ISSUE TITLE
Peak calling error

### ISSUE THREAD

**Issue by sylestiel** [wbaopaul/scATAC-pro#26]
alling peaks ...
--Using MACS2... 
INFO  @ Fri, 24 Jul 2020 21:03:22: 
# Command line: callpeak -t home/salappa/output/mapping_result/P2_9.positionsort.MAPQ30.bam --outdir output/peaks/MACS2 -n P2_9 -f BAM -q 0.01 -g hs
# ARGUMENTS LIST:
# name = P2_9
# format = BAM
# ChIP-seq file = ['home/salappa/output/mapping_result/P2_9.positionsort.MAPQ30.bam']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Fri, 24 Jul 2020 21:03:22: #1 read tag files... 
INFO  @ Fri, 24 Jul 2020 21:03:22: #1 read treatment tags... 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 653, in <module>
    main()
  File "/usr/local/bin/macs2", line 51, in main
    run( args )
  File "/usr/local/lib64/python3.6/site-packages/MACS2/callpeak_cmd.py", line 65, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/usr/local/lib64/python3.6/site-packages/MACS2/callpeak_cmd.py", line 387, in load_tag_files_options
    tp = options.parser(options.tfile[0], buffer_size=options.buffer_size)
  File "MACS2/IO/Parser.pyx", line 1063, in MACS2.IO.Parser.BAMParser.__init__
  File "/usr/lib64/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib64/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'home/salappa/output/mapping_result/P2_9.positionsort.MAPQ30.bam'
Error in library(data.table) : there is no package called ‘data.table’
Execution halted
Error: Unable to open file output/peaks/MACS2/P2_9_peaks.narrowPeak. Exiting.
Error in library(data.table) : there is no package called ‘data.table’
Execution halted
Call peaks done !

**Comment by wbaopaul** [comment]
To me, you are using mouse genome mm10 but the above message indicates you are using human genome (-g hs). You need to change configure_user.txt file like:
`MACS2_OPTS = -q 0.01 -g mm` 
or
`MACS2_OPTS = -q 0.01 -g mm --nomodel --extsize 200 --shift -100`

**Comment by sylestiel** [comment]
Thank you!
However, can you clarify the difference between the two commands?

**Comment by wbaopaul** [comment]
You can find the meaning of MACS2 parameters here: https://github.com/macs3-project/MACS

**Comment by sylestiel** [comment]
Still having problems with call_peaks function!!!!

[configure_user.txt](https://github.com/wbaopaul/scATAC-pro/files/4990311/configure_user.txt)

--------------------------------------------
Tue Jul 28 12:12:04 CDT 2020
Calling peaks ...
--Using MACS2... 
INFO  @ Tue, 28 Jul 2020 12:12:05: 
# Command line: callpeak -t /home/salappa/output/mapping_result/P2_9.positionsort.MAPQ30.bam --outdir output/peaks/MACS2 -n P2_9 -f BAM -q 0.01 -g mm --nomodel --extsize 200 --shift -100
# ARGUMENTS LIST:
# name = P2_9
# format = BAM
# ChIP-seq file = ['/home/salappa/output/mapping_result/P2_9.positionsort.MAPQ30.bam']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Tue, 28 Jul 2020 12:12:05: #1 read tag files... 
INFO  @ Tue, 28 Jul 2020 12:12:05: #1 read treatment tags... 
struct.error: unpack requires a buffer of 4 bytes
Exception ignored in: 'MACS2.IO.Parser.BAMParser.tsize'
struct.error: unpack requires a buffer of 4 bytes
INFO  @ Tue, 28 Jul 2020 12:12:05: 0 reads have been read. 
INFO  @ Tue, 28 Jul 2020 12:12:05: #1 tag size is determined as 0 bps 
INFO  @ Tue, 28 Jul 2020 12:12:05: #1 tag size = 0.0 
INFO  @ Tue, 28 Jul 2020 12:12:05: #1  total tags in treatment: 0 
INFO  @ Tue, 28 Jul 2020 12:12:05: #1 user defined the maximum tags... 
INFO  @ Tue, 28 Jul 2020 12:12:05: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
INFO  @ Tue, 28 Jul 2020 12:12:05: #1  tags after filtering in treatment: 0 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 653, in <module>
    main()
  File "/usr/local/bin/macs2", line 51, in main
    run( args )
  File "/usr/local/lib64/python3.6/site-packages/MACS2/callpeak_cmd.py", line 104, in run
    info("#1  Redundant rate of treatment: %.2f", float(t0 - t1) / t0)
ZeroDivisionError: float division by zero
Error in fread(peak_file, header = F) : 
  File 'output/peaks/MACS2/P2_9_peaks.narrowPeak' does not exist or is non-readable. getwd()=='/home/salappa'
Execution halted
Error: Unable to open file output/peaks/MACS2/P2_9_peaks.narrowPeak. Exiting.
Warning message:
In fread(peakFile) :
  File 'output/peaks/MACS2/P2_9_features_BlacklistRemoved.bed' has size 0. Returning a NULL data.table.
Error in setnames(x, value) : 
  Can't assign 3 names to a 0 column data.table
Calls: names<- -> names<-.data.table -> setnames
Execution halted
Call peaks done !

**Comment by sylestiel** [comment]
Hi,
my Mapping function did not work. Despite adding the genome.fa file to the bwa_mm10_index folder. The files produced are scrambled and just a few bytes in size. 
I guess it goes without saying that the call_peak function would not work.
Attached is the configure user text that has been modified. Can you check if there is anything amiss?
[configure_user.txt](https://github.com/wbaopaul/scATAC-pro/files/4996170/configure_user.txt)

**Comment by wbaopaul** [comment]
I think the configure file seems OK to me. Please tell more about how did you run it and what's the error message. I have no clue for now.

**Comment by sylestiel** [comment]
/opt/scATAC-pro/scATAC-pro_1.1.4/scATAC-pro -s mapping -i /home/salappa/output/trimmed_fastq/P2_9.trimmed.demplxed.PE1.fastq.gz,/home/salappa/output/trimmed_fastq/P2_9.trimmed.demplxed.PE2.fastq.gz, -c /home/salappa/scATAC-pro_analysis/configure_user.txt
[logs.zip](https://github.com/wbaopaul/scATAC-pro/files/4996401/logs.zip)

**Comment by wbaopaul** [comment]
There is a typo of your command. There should be no ',' before -c.

**Comment by sylestiel** [comment]
[mapping.log](https://github.com/wbaopaul/scATAC-pro/files/4996564/mapping.log)

Still no luck!

**Comment by wbaopaul** [comment]
Seems bwa cannot locate the index file. Can you double check your index file path or try re-download the index file folder: https://chopri.app.box.com/s/dlqybg6agug46obiu3mhevofnq4vit4t (called mm10_bwa_index1).

**Comment by wbaopaul** [comment]
@sylestiel Is your mapping issue solved? Thanks.

**Comment by sylestiel** [comment]
I ran out of space on the Virtual Machine. Waiting to resolve that to test again.

**Comment by wbaopaul** [comment]
I will close this issue since no update for several months.
