### ISSUE TITLE
Can not run the “MACS2” to do “call_peak”, and also can not run the “clustering” with our 10xgenomics “matrix data” 

### ISSUE THREAD

**Issue by hcluo2012** [wbaopaul/scATAC-pro#27]
1.	It’s successful to run demplx_fastq or mapping function with the scATAC-pro program, and we have got some results.
2.	However, we can not run the “MACS2” to do “call_peak”, and we also can not run the “clustering” with our 10xgenomics “matrix data” which already first run by cellranger-atac program from 10xgenomics.
3.	The program is as follows:
scATAC-pro -s mapping -i output/trimmed_fastq/WT-LK-original.trimmed.demplxed.PE1.fastq.gz,output/trimmed_fastq/WT-LK-original.trimmed.demplxed.PE2.fastq.gz -c configure_WT-LK.txt

scATAC-pro -s call_peak  -i output/mapping_result/WT-LK-original.positionsort.MAPQ30.bam  -c configure_WT-LK.txt

scATAC-pro -s clustering -i output/filtered_matrix/PEAK_CALLER/CELL_CALLER/matrix.mtx -c configure_WT-LK.txt

Hope for your kind suggestions.  Thanks a lot.

My configure file is as follows:

######################################################################
######################################################################

######################################################################
######################################################################
OUTPUT_PREFIX = WT-LK-original     ## prefix for ouput file name
isSingleEnd = FALSE         ## scTHS-seq uses single end sequencing

## annotation files (blacklist, promoters, enhancers, TSS, etc)
BLACKLIST = annotation/mm10_blacklist.bed
PROMOTERS = annotation/mm10_promoter.bed
ENHANCERS = annotation/mm10_enhancer.bed
TSS = annotation/mm10_tss.bed
CHROM_SIZE_FILE = annotation/chrom_mm10.sizes

GENOME_NAME = mm10   ## used for TF motif enrichemnt and footprinting analysis
plotEPS = TRUE  ## print figures in eps format when generating summary report

#####################################
#####################################
#TRIM_METHOD = Trimmomatic   ## one of trim_galore (default), Trimmomatic or not specified (means DONOT trim)

## you dont need to specify this if your TRIM_METHOD is trim_galore or not specified
#ADAPTER_SEQ = /projects2/LuoLab/Luo/reference/trim/NexteraPE-PE.fa

#########################################################
#########################################################

MAPPING_METHOD = bwa  ## one of bwa/bowtie/bowtie2

## extra mapping options (NO NEED TO SPECIFY INPUT FASTQS AND OUTPUT FILE/DIRECTORY)
BWA_OPTS = -t 16
BWA_INDEX = mm10_genome/genome.fa

#BOWTIE_OPTS = --quiet -p 16 
#BOWTIE_INDEX = bowtie-1.2.2/indexes/GRCm38/GRCm38_no_alt

#BOWTIE2_OPTS = --end-to-end -p 16
#BOWTIE2_INDEX = bowtie2.2.9/indexes/GRCm38/GRCm38_no_alt

#MAPQ = 30  ## filter bam by MAPQ for downstream analysis 
#CELL_MAP_QC = TRUE  ## output mapping stats for cell barcodes

#################################################################################
#################################################################################

PEAK_CALLER = MACS2  ## one of MACS2, BIN, and COMBINED

## (change -g mm if you are using mouse data) 

#MACS2_OPTS = -q 0.01 -g mm 

## or something like this to ignore building shifting model 
MACS2_OPTS = -q 0.01 -g mm --nomodel --extsize 200 --shift 100

BIN_RESL = 5000    ## bin resolution in bp

########################################################
########################################################
CELL_CALLER = FILTER  ## EmptyDrop/cellranger/FILTER

EmptyDrop_FDR = 0.001

# set cutoff to define cell if CELL_CALLER is specified as FILTER
# ignored if CELL CALLER was specified other than FILTER
FILTER_BC_CUTOFF = --min_uniq_frags 3000 --max_uniq_frags 50000 --min_frac_peak 0.5 --min_frac_tss 0.0 --min_frac_promoter 0 --min_frac_enhancer 0.0 --max_frac_mito 0.1

##############################################################################
##############################################################################
norm_by = tf-idf ## or log (just log transformation) or NA
Top_Variable_Features = 10000 ## number/fraction of variable features used for seurat
REDUCTION = pca  ## pca/lda, note that UMAP and TSNE will be automatically calculated correspondly
nREDUCTION = 30 ## the reduced dimension
CLUSTERING_METHOD = seurat  ## seurat/cisTopic/kmeans/LSI/SCRAT/chromVAR/scABC
K_CLUSTERS = NULL  ## the number of cluster, will set resolution as 0.2 if it's NULL
prepCello = TRUE  ## generate object for VisCello (for visualization)

#######################################################################################
#######################################################################################
RUN_DA = TRUE  ## run differential analysis or not
group1 = 0:1   ## either one or multiple names, separated by colon, or 'one'
group2 = 2     ## cluster name as above or 'rest'
test_use = wilcox  ## one of negbinom, LR, wilcox, t, DESeq2

#######################################################################################
#######################################################################################
RUN_GO = TRUE ## run GO analysis after DA
GO_TYPE = BP  ## BP/CC/kegg

#######################################
#######################################
SPLIT_BAM2CLUSTER = TRUE

##################################################################
##################################################################
DO_FOOTPRINT = FALSE

## comparing two groups, set similarly as in doing DA
group1_fp = 0   ## either one cluster name or 'one'
group2_fp = 1   ## cluster name as above or 'rest'
pvalue_fp = 0.05

############################################################################
###########################################################################
RUN_Cicero = TRUE
## plot interactions within Cicero_Plot_Region on the summary report  
Cicero_Plot_Region = chr6:52126006-52224459 

############################################################################
############################################################################
Integrate_By = VFACS  ## VFACS, seurat, pool or harmony 
prepCello4Integration = TRUE ## prepare cello for integrated object

**Comment by wbaopaul** [comment]
Can you show me the log file for the` call_peak` module, which is located at output/logs/call_peak.log?
BTW, the `clustering `module does not support 10x cellranger style matrix as input. The row name is slight different.

**Comment by wbaopaul** [comment]
I will close this issue because the error rised from unsuccessfully installation of scATAC-pro and we have solved it through independent email.
