### ISSUE TITLE
read configuration error in singularity image

### ISSUE THREAD

**Issue by breannesparta** [wbaopaul/scATAC-pro#28]
Hi, 

When I use singularity to run scATAC-pro convert10xbam, in the output/logs/ I get the file: convert10xbam.log:

Aligning ...
/usr/local/bin/scATAC-pro_1.1.4/scripts/read_conf.sh: line 14: export: `
=': not a valid identifier
make: *** [/usr/local/bin/scATAC-pro_1.1.4/scripts/Makefile:92: convert10xbam] Error 1

Thanks!

**Comment by wbaopaul** [comment]
How did you run the module? I guess there is some problem in specifying input files.

**Comment by breannesparta** [comment]
Thanks for the reply, I ran:

singularity exec -H /media/timothyhamilton/data1/Tim_Hamilton/Breanne/scATAC/PCA01 --cleanenv /media/timothyhamilton/data1/Tim_Hamilton/Breanne/scATAC/PCA01/scatac-pro.simg scATAC-pro -s convert10xbam -i  possorted_bam.bam -c configure_user.txt -o output

**Comment by wbaopaul** [comment]
Seems you ran it correctly. That's weird. This module in singularity version was tested and work properly for me. The only difference is that you have .simg and I have .sif image format, which I am not sure should be a problem...

**Comment by breannesparta** [comment]
Yes, also this might be unrelated, but, when I tried to install scATAC-pro from github (using make configure prefix=/home/breanne/scATAC-pro) on the same machine, I received these errors: 

scripts/install/Makefile:25: recipe for target 'configure' failed
make[1]: *** [configure] Error 1
make[1]: Leaving directory '/home/breanne/scATAC-pro'
Makefile:40: recipe for target 'configure' failed
make: *** [configure] Error2

**Comment by wbaopaul** [comment]
1)For singularity version, can you pull the image, get .sif format and try it again?
2) Did you git clone the software into /home/breanne/scATAC-pro? If this is the case, can you try to use different prefix?
Hope it helps,

**Comment by wbaopaul** [comment]
I will close this issue since no further update for several months.
