### ISSUE TITLE
Error in fread(region.file, select = 1:3, header = F)

### ISSUE THREAD

**Issue by YOU-k** [wbaopaul/scATAC-pro#29]
Hi, I was trying to use singularity to run scATAC-pro. 
And it worked all good until  get_mtx, 
The code I used was
`singularity exec --cleanenv -H $scATACpro scatac-pro_latest.sif scATAC-pro -s get_mtx \
             -i $OUTDIR/peaks/MACS2/${OUTPUT_PREFIX}_features_BlacklistRemoved.bed \
             -c $CONFIG `
and i got an error in get_mtx.log that
> frags[, 'depth_per_bc' := .N, by = bc]
> frags = frags[depth_per_bc > min_total_frag]
> frags[, depth_per_bc := NULL]
> 
> regions = fread(region.file, select=1:3, header = F)
Error in fread(region.file, select = 1:3, header = F) : 
  File 'output/raw_matrix/MACS2' is a directory. Not yet implemented.
Execution halted
make: *** [/usr/local/bin/scATAC-pro_1.1.4/scripts/Makefile:133: get_mtx] Error 1.

Is there any suggestion how to solve this?
Thanks!

**Comment by wbaopaul** [comment]
You need to specify fragment file for this module like:
```
 $ scATAC-pro -s get_mtx 
                 -i output/summary/pbmc10k.fragments.txt,output/peaks/MACS2/pbmc10k_features_BlacklistRemoved.bed 
                 -c configure_user.txt 
```

**Comment by YOU-k** [comment]
It works! Thanks

**Comment by YOU-k** [comment]
Sorry I came across another problem. when I start to call cell and run -s call_cell
It says can't find output/raw_matrix/PEAK_CALLER/
$ scATAC-pro -s call_cell
                 -i output/raw_matrix/PEAK_CALLER/matrix.mtx
                 -c configure_user.txt
And I only found a matrix.mtx in /raw_matrix/MACS2/matrix.mtx. So I run with it. However, I only get about 180 cells. I got 670 if I use Cell Ranger. What might be the problem? Thanks!

**Comment by wbaopaul** [comment]
1) what is your PEAK_CALLER (PEAK_CALLER is a parameter, it's specified in your configure user file), it shoul be either MACS2 or COMBINED or BIN. In you case, it should be `-i output/raw_matrix/MACS2/matrix.mtx`
2) scATAC-pro used different ways/cutoff to call cells than cellranger. You can specify them in your configure_user.txt file. The default setting is kind of stringent, in which I required 50% reads in peaks and total number of fragments greater than 3000, and the percentage in mitochondrial genome less than 10%.  You can play with these cutoffs.  You can also check how many peaks you have in your output/peaks/MACS2/. If there are too few peaks (less than 50000, just my impression), which usually indicates the data quality is not good. The default setting of MACS2 is also kind of stringent:  `MACS2_OPTS = -q 0.01 -g hs --nomodel --extsize 200 --shift -100`, you can also change qvalue to get more peaks.
