### ISSUE TITLE
Docker isn't working

### ISSUE THREAD

**Issue by mvinyard** [wbaopaul/scATAC-pro#3]
Docker image leads to an error.

**Comment by wbaopaul** [comment]
Can you give more details about the error?  How did you run the image and what's the error message? 

Thanks a lot,
Wenbao

**Comment by mvinyard** [comment]
When you click this link, you get a 500 error
![Screen Shot 2019-12-02 at 5 03 31 PM](https://user-images.githubusercontent.com/47393421/69999057-be5d9a00-1525-11ea-829d-bbd211e21cb7.png)

**Comment by wbaopaul** [comment]
Updated. I forgot to log out of docker hub when I copy the link. It should work now. Just a remind, you can also use option 2,3 or4 to run the dockerized version.

Thanks,
Wenbao
