### ISSUE TITLE
barcode name in sam tag

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#32]
Hi, happy new year!

I see that bam files generated by scATAC-pro does not have barocode name in sam tag but rather in sequencing read name, if my understandign is correct. This limits using many other tools such as "bap" and "cellSNP." Would it be possible to tell us how to add the barcode info in the sam tag. It would be cool if you could provide a bash file with scATAC-pro to additionally add them to the bam files generated.

Thank you!!

**Comment by wbaopaul** [comment]
Thanks. I would be happy to add this information. Can you give an example of reqired bam format, i.e., what is the read look like in the bam/sam file? I am not sure which column to add the barcode. 
Thanks.

**Comment by AnjaliC4** [comment]
Hi, I have attached example bam file here where 'CB' refers to barcode tag and 'BC' refers to sample_index.
Many tools look for these tags to analyze, so adding them back to bam file would be great. If you could please add a module for this, that would be so great. Thanks a lot!!

<img width="1438" alt="Screen Shot 2021-01-15 at 11 34 43 AM" src="https://user-images.githubusercontent.com/60046859/104753487-10f81680-5726-11eb-981a-cd3073cde2ae.png">

**Comment by wbaopaul** [comment]
I created a new module 'addCB2bam' in the _dev_ branch. You can install it from _dev_ branch for now: 
(`git clone -b dev wbaopaul/scATAC-pro;
git configure prefix=xxx ; git install`). Basically this module will write the cell barcode information in the name into column "CB:Z:barcode" as the last column of the bam file.
Please let me know if you have any problem. Alternatively, you can do it by your self using similar script like this:

```
samtools view -h  Your_BAM_FILE |awk '{ if($0 ~ "^@") {print $0} else {split($1,a,":"); print $0"\tCB:Z:"a[1]} }' > tmp.sam
samtools view -b tmp.sam > Updated_BAM_File

```

**Comment by AnjaliC4** [comment]
Thanks a lot for adding this promptly. I will use it and let you know if I face any functionality issues.

**Comment by AnjaliC4** [comment]
It works very well! Thank you very much!!

**Comment by wbaopaul** [comment]
Great to hear that!
