### ISSUE TITLE
The installation failed

### ISSUE THREAD

**Issue by Ping-lin14** [wbaopaul/scATAC-pro#33]
Hi

When i run `make configure prefix=/home/pinglin/atac_tool`,
received error message 
![image](https://user-images.githubusercontent.com/69965537/106387747-1f2c7f00-6416-11eb-962a-fa606a855a0a.png)
I have R 4.0, 3.6 and 3.2.2 at the same time.
What should I do?

**Comment by wbaopaul** [comment]
I think your default R is 3.2.2. You can check this by type 'which R' command in your terminal. Before install scATAC-pro, change your default R path use this: export PATH="YOU_PREFERED_R_PATH:$PATH". You may try R/3.6 first. (I haven't tested scATAC-pro under R4.0).

**Comment by Ping-lin14** [comment]
Thank you for your reply, the question has been resolved.
