### ISSUE TITLE
Is Perl required for the mapping function?

### ISSUE THREAD

**Issue by philyang07** [wbaopaul/scATAC-pro#35]
Hi,

I was just taking a look at the `mapping.sh` script, and it seems like Perl is used to get the fragment information, but it isn't listed as a required programming language?

```echo "Getting txt file for read pair (fragment) information"
${PERL_PATH}/perl ${curr_dir}/src/simply_bam2frags.pl --read_file ${mapRes_dir}/${OUTPUT_PREFIX}.positionsort.MAPQ${MAPQ}.bam \
        --output_file ${qc_dir}/${OUTPUT_PREFIX}.fragments.txt --samtools_path $SAMTOOLS_PATH```

**Comment by wbaopaul** [comment]
Right, Perl was used. Thanks for pointing this out. I didn't specify perl since perl is automatically installed in most linux system. WIll add it to the requirement list.
