### ISSUE TITLE
Error during preprocessing (file already exists??)

### ISSUE THREAD

**Issue by philyang07** [wbaopaul/scATAC-pro#36]
Hi @wbaopaul,

I've tried to test scATAC-pro using the process function, but in the logs, the following error occurs:

```make[1]: Entering directory '/home/phily/repos/scATAC-pro'
--------------------------------------------
Mon Feb 15 11:41:19 AWST 2021
Preprocessing ...
error: output/demplxed_fastq/demplxed_testfastq_S1_L002_R1_001.fastq already exists, remove it first!
mv: cannot stat 'output/demplxed_fastq/demplxed_testfastq_S1_L002_R1_001.fastq': No such file or directory
/home/phily/myapps/scATAC-pro/scATAC-pro_1.2.0/scripts/Makefile:180: recipe for target 'process' failed
make[1]: *** [process] Error 1
make[1]: Leaving directory '/home/phily/repos/scATAC-pro'
```

I don't know why `error: output/demplxed_fastq/demplxed_testfastq_S1_L002_R1_001.fastq already exists, remove it first!
` occurs, as inside the output folder that file is not there.

**Comment by wbaopaul** [comment]
It is weird to me either. Can you tell me more about how did you run it? Thanks.

**Comment by philyang07** [comment]
Hi @wbaopaul,

I figured out what I did wrong. When I first ran it I used an incorrect filename, and didn't delete the demultiplexed fastq file before running it again, which is why it said the file already exists.
