### ISSUE TITLE
Error: assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE

### ISSUE THREAD

**Issue by philyang07** [wbaopaul/scATAC-pro#37]
Hi @wbaopaul,

When running the process function, an error occurs when the get_mtx.R script is being run (line 112):

The error:
```
> smat = sparseMatrix(i = mtx$rowID, j = mtx$colID, x = mtx$count,
+                     dimnames = list(features, bcs))
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: sparseMatrix -> <Anonymous>
Execution halted
```

The line causing the error:
```
smat = sparseMatrix(i = mtx$rowID, j = mtx$colID, x = mtx$count,
                    dimnames = list(features, bcs))
```

I will attach my input FASTQ files as well as the log file.

[process.log](https://github.com/wbaopaul/scATAC-pro/files/5987858/process.log)

[inputFASTQs.zip](https://github.com/wbaopaul/scATAC-pro/files/5987871/inputFASTQs.zip)

**Comment by wbaopaul** [comment]
Can you check the mapping result? and what's your configure_user.txt file? I feel there may be something abnormal as early as in mapping step. Please also check output of other steps to see any abnormility. Anoter issue is your data is so small, maybe no barcode was left after default filtering in get_mtx.R (a barcode with less than 5 reads in peaks was filtered). 

Generally, if you want to test scATAC-pro, you probabaly need to run it step by step which is easier to trouble shooting. Thanks.

**Comment by wbaopaul** [comment]
I am closing this issue since no further response for more than 2 months.
