### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by cadyyuheng** [wbaopaul/scATAC-pro#39]
Hi,

I was trying to install the package but got this error (shown below). Could someone help me with this? I'm not so sure how to check my install path. Thanks!

make configure prefix=/home/yfy/
make -f ./scripts/install/Makefile PREFIX=/home/yfy
make[1]: Entering directory `/home/yfy'
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting scATAC-pro installation ...
Dependencies will be install in /home/yfy6677
Can not proceed without R, please install and re-run
make[1]: *** [configure] Error 1
make[1]: Leaving directory `/home/yfy6677/scATAC-pro'
make: *** [configure] Error 2

**Comment by wbaopaul** [comment]
The message tells that you don't have R installed. You need R (>3.6.1) and python 3 (>3.6) for scATAC-pro. Your install path should be fine.

**Comment by cadyyuheng** [comment]
thanks, @wbaopaul for your reply! I'm running on the Linux system and I do have R installed. Do I need to specify my R directory or do something such it could be recognized?

**Comment by cadyyuheng** [comment]
so after manually load R, I encountered this error:
(base) [yfy@quser23 scATAC-pro]$ make install                                                                                                            Installing ...
cp: cannot copy a directory, ‘/home/yfy/scATAC-pro’, into itself, ‘/home/yfy/scATAC-pro/scATACpro/scATAC-pro_1.2.1’
make: *** [cp] Error 1

**Comment by wbaopaul** [comment]
you are trying to install scATAC-pro into your scATAC-pro source codes folder. You can specify a new path.

**Comment by cadyyuheng** [comment]
Thanks @wbaopaul ! The problem is now solved.
