### ISSUE TITLE
"Error in if (sum (dist_mat> distance_constraint) / 2 <1)" is reported when running runCicero

### ISSUE THREAD

**Issue by lidenghui92** [wbaopaul/scATAC-pro#4]
hello,
       When I ran runCicero, I encountered some problems, as follows: 
################################
[1] "Starting Cicero"
[1] "Calculating distance_parameter value"
Error in if (sum(dist_mat > distance_constraint)/2 < 1) { :
  missing value where TRUE/FALSE needed
Calls: doCicero_gascore ... estimate_distance_parameter -> find_distance_parameter
In addition: Warning messages:
1: In order(as.character(dhsinfo$chr), as.numeric(as.character(dhsinfo$bp2))) :
  NAs introduced by coercion
2: In make_atac_cds(dt, binarize = T) : NAs introduced by coercion
3: In make_atac_cds(dt, binarize = T) : NAs introduced by coercion
Execution halted
#####################
I have tried many ways and still can't solve it, so ask your help.

Thanks

**Comment by wbaopaul** [comment]
Looks like the error arises from the format of the input for cicero. Can you tell me more detail about how did you run it, for instance, What other modules have you run before running runCicero module? Did you specify TSS file path and CHROM_SIZE_FILE in the configure_user.txt file?

Thanks,
Wenbao

**Comment by lidenghui92** [comment]
Thank you for your reply. I run according to [https://github.com/wbaopaul/scATAC-pro#run-scatac-pro-step-by-step](url), before running runCicero module, I have run the demplx_fastq,trimming,mapping,call_peak,aggr_signal,get_mtx,qc_per_barcode,call_cell,get_bam4Cells,clustering,motif_analysis,split_bam,footprint,runDA,runGO.  I have specified the TSS file and CHROM_SIZE_FILE path in the configure_user.txt file.

Thank you a lot,
denghui

**Comment by lidenghui92** [comment]
I suspect that the error may be related to the reference genome format. In your article, you just said that you use the "GRCh38" genome, but did not say where to download it. I used the hg38 genome downloaded from UCSC for testing. Is this correct?Looking forward for your response

thank you
denghui

**Comment by wbaopaul** [comment]
Thanks to tell me those details. Download hg38 genome from UCSC should be OK, and the chromosome name in your TSS file is in "chr" style not in numeric, right? Or can you check the rownames of your seurat_obj? or can you somehow share a small seurat_obj.rds file that I can reproduce your error?

Thanks,
Wenbao

**Comment by lidenghui92** [comment]
My annotated files(vesion hg38) are all downloaded from github [https://github.com/wbaopaul/scATAC-pro/tree/master/annotation](url), and the TSS style looks like this:
############
chr1    11868   11869   DDX11L1 .       +       transcribed_unprocessed_pseudogene
chr1    12009   12010   DDX11L1 .       +       transcribed_unprocessed_pseudogene
chr1    17435   17436   MIR6859-1       .       -       miRNA
chr1    29553   29554   RP11-34P13.3    .       +       lincRNA
chr1    29569   29570   WASH7P  .       -       unprocessed_pseudogene
################

my seurat_obj.rds file rownames ooks like this: 

################
 [1] "chr1-1000274-1000627,HES4"
 [2] "chr1-1000319-1000749,HES4"
 [3] "chr1-1000335-1000886,HES4"
 [4] "chr1-100037410-100037932,MFSD14A"
 [5] "chr1-100037546-100037961,MFSD14A"
 [6] "chr1-100037660-100037989,MFSD14A"
 [7] "chr1-100037769-100038109,MFSD14A-Tss"
 [8] "chr1-100037798-100038131,MFSD14A-Tss"
 [9] "chr1-100037981-100038338,MFSD14A-Tss"
[10] "chr1-100037981-100038512,MFSD14A-Tss"
[11] "chr1-100038096-100038608,MFSD14A-Tss"
[12] "chr1-100038147-100038642,MFSD14A"
#################

I am trying to send the seurat_obj.rds file to you because it is too big. hope you can help to solve it.

Thanks,
Denghui

**Comment by lidenghui92** [comment]
hello,
       I don't know how to truncate the seurat_obj.rds, so I uploaded the entire file to GitHub[https://github.com/lidenghui92/scATAC-pro-test/raw/master/seurat_obj.rds](url).Looking forward for your response

Thank you
Denghui

**Comment by lidenghui92** [comment]
hello,
    This is the small seurat_obj.rds file. Looking forward for your response
[small_seurat_obj.zip](https://github.com/wbaopaul/scATAC-pro/files/3989015/small_seurat_obj.zip)

Thanks you a lot

Denghui

**Comment by wbaopaul** [comment]
I am not able to use your full size seurat_obj, which cannot be read by readRDS.

I can use your small seurat obj, I run cicero step by step using defualt parameters: got following warning and error message:
> cicero_cds <- make_cicero_cds(input_cds, reduced_coordinates = redu.coords)
Overlap QC metrics:
Cells per bin: 50
Maximum shared cells bin-bin: 44
Mean shared cells bin-bin: 7.05241379310345
Median shared cells bin-bin: 0
Warning message:
In make_cicero_cds(input_cds, reduced_coordinates = redu.coords) :
  On average, more than 10% of cells are shared between paired bins.
>    conns <- run_cicero(cicero_cds, chr_sizes)
[1] "Starting Cicero"
[1] "Calculating distance_parameter value"
Error in if (sum(dist_mat > distance_constraint)/2 < 1) { : 
  missing value where TRUE/FALSE needed

It looks like the format is right, the error may arise because this warning: "On average, more than 10% of cells are shared between paired bins."  I am not sure how to fix this error.

Maybe you can try Cicero directly with your filtered matrix, cicero has recently supported10x style matrix data, you can use scATAC-pro outputed cell-by-peak matrix as input:
https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#loading-10x-scatac-seq-data. By this approach you may try differnt paramters.

**Comment by lidenghui92** [comment]
Thanks, I will try it . 

I have another question about report module，when I run the report module， I can‘t get the final "scATAC-pro_report_cellranger.html" file and get the following error ：
####################
label: unnamed-chunk-11 (with options)
List of 2
 $ fig.height: num 9
 $ out.width : chr "\\textwidth"

No methods found in package 'IRanges' for request: 'score' when loading 'TFBSTools'
Quitting from lines 343-458 (scATAC-pro_report.Rmd)
Error in chromVar.obj@assays$data :
  $ operator not defined for this S4 class
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> do_DA -> rownames
In addition: Warning messages:
1: In fread(tss_escore_file) :
  Detected 1 column names but the data has 246 columns (i.e. invalid file). Added 245 extra default column names at the end.
2: Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
Please use `as_label()` or `as_name()` instead.
This warning is displayed once per session.

Execution halted
####################
Sorry to bother you and look forward to your reponse.

Thanks you a lot

Denghui

**Comment by wbaopaul** [comment]
Looks like something wrong with chromVar_obj.rds. Can you double check whether there is any error when you ran motif_analysis. There is a log file under output/logs/motif_analysis.log, which will tell you detailed running message. Or you can read this object in R: library(chromVAR)
chromVar.obj = readRDS('YOUR chromVar_obj.rds') and check chromVar.obj@assays$data$dev ...

Best,
Wenbao

**Comment by lidenghui92** [comment]
This is the log file
[motif_analysis.log](https://github.com/wbaopaul/scATAC-pro/files/3991457/motif_analysis.log).

And i read chromVar_obj.rds in R， it shows below：
![motif_error1](https://user-images.githubusercontent.com/41458088/71309247-aa2ffd00-2440-11ea-8fa7-ede43d90f1eb.jpg)
So,I checked the data structure of chromVar_obj.rds and it shows as follows
![str(chromVar obj)](https://user-images.githubusercontent.com/41458088/71309312-7a352980-2441-11ea-8465-8af1ed736a17.jpg)

Based on the above information, do I need to download the "TFBSTools" package again to solve this problem? Or errors caused by other reasons

Thanks
Denghui

**Comment by wbaopaul** [comment]
Thanks for sharing the running log. The error arises from the inconsitent way of accessing differnt version of chromVar objects. (My vesion of chromVAR is 1.6.0 I guess yours is version 1.8.0). I just updated the script for generating summary report. It should work for your case now.

Thanks again,
Wenbao

**Comment by wbaopaul** [comment]
> hello,
> When I ran runCicero, I encountered some problems, as follows:
> ################################
> [1] "Starting Cicero"
> [1] "Calculating distance_parameter value"
> Error in if (sum(dist_mat > distance_constraint)/2 < 1) { :
> missing value where TRUE/FALSE needed
> Calls: doCicero_gascore ... estimate_distance_parameter -> find_distance_parameter
> In addition: Warning messages:
> 1: In order(as.character(dhsinfo$chr), as.numeric(as.character(dhsinfo$bp2))) :
> NAs introduced by coercion
> 2: In make_atac_cds(dt, binarize = T) : NAs introduced by coercion
> 3: In make_atac_cds(dt, binarize = T) : NAs introduced by coercion
> Execution halted
> #####################
> I have tried many ways and still can't solve it, so ask your help.
> 
> Thanks

I guess this issue was solved. I got the same error as yours in another data and I removed those peaks who are not belong to any chr in the chrom_size_file.  Those peaks are removed in my latest commit.
Hope it works for your data too.
Wenbao
