### ISSUE TITLE
Strange result

### ISSUE THREAD

**Issue by Ping-lin14** [wbaopaul/scATAC-pro#40]
HI 

After completing the clustering function, I first go to R to confirm seurat_obj.
However I received a strange UMAP. This is very different from the result I got in Signac.
Do you have any clue?
![Rplot](https://user-images.githubusercontent.com/69965537/108952468-7c79c000-76a4-11eb-9d60-f3b736451387.png)

**Comment by wbaopaul** [comment]
That's very strange to me either. Can you tell me more detail about how you run it and what's the configure_user.txt looks like? Did you generate html report file which can show you some qc metrics. Without those information, I don't have any sense of this result.

**Comment by Ping-lin14** [comment]
Due to space issues, when I execute the process function to aggr_signal, I can't do it, so after moving the previously output files to disk, I gradually perform aggr_signal, get_mtx, qc_per_barcode, call_cell, get_bam4Cells. When generating the report file, I received the message `Error in plot_connections(conns, chr0, start0, end0, gene_model = gene_anno, :No peaks in the specified range, nothing to plot!`

[configure_user.txt](https://github.com/wbaopaul/scATAC-pro/files/6037504/configure_user.txt)

**Comment by wbaopaul** [comment]
Thanks for providing those information. The error rised from there is no chromatin interaction found in the region specified in the configure_user.txt file (By default, the plot region is chr5:140610000-140640000). You can either change the region or move/delete the cicero_interactions.txt file from the downstream folder to bypass this plot. (I will add an option to let user to skip this plot in next update.) You should get some figures and tables already under output/summary/. Please let me know anything abnormal. 

Hope it helps,
Thanks.

**Comment by wbaopaul** [comment]
Beyond that, the number of variable features selected may play a critical role. The default number is 10000 (Top_Variable_Features = 10000 in the configure_user.txt file), you may play with a smaller number, say 5000 or even smaller for instance.

**Comment by Ping-lin14** [comment]
I pay the html report file generated by bypassing the cicero_interactions.txt file.
[scATAC-pro_report.zip](https://github.com/wbaopaul/scATAC-pro/files/6040312/scATAC-pro_report.zip)

**Comment by wbaopaul** [comment]
The umap on the report seems very normal to me and it is quite different from the one you post above. The two are supposed to be the same. 
Overall, the %mito reads are a bit high and the TSS enrichment score is not high, which suggests the overall data quality is not very good.

**Comment by wbaopaul** [comment]
I am closing this issue since no further comment received in the past two months.
