### ISSUE TITLE
working with Integrated data

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#42]
Hi,

I integrated my data using harmony, but how do I do DA/TF motif/footprinting and others on the integrated data? I gave the path to integrated rds object but it seems like it needs path to an integrated filtered_matrix as well. 
Thanks!

**Comment by wbaopaul** [comment]
With the integrated seurat object, you can follow [this tutorial](https://scatacpro-in-r.netlify.app/redo_downstream_in_r) to do some downstream analysis in R.  For TF motif analysis, you need to output a matrix obj from that integrated seurat obj.  The footprinting analysis, which needs merged bam files from different individuals, is not currently supported in scATAC-pro.  I will probably add more downstrame analysis option for the integrated data for next update of scATAC-pro (like let the integrated obj be acceptable input for those DA/TF_motif analysis steps ). Thanks!

**Comment by wbaopaul** [comment]
I just realse version 1.3.0, which should be more friendly to the integrated data.

**Comment by wbaopaul** [comment]
I am closing this issue since no further response for more than 3 months.
