### ISSUE TITLE
filtered atac.fragments.txt

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#43]
Hi,

If my understanding is correct, atac.fragments.txt is produced from atac.bam and not atac.bam.MAPQ30.
How can I filter atac.fragments.txt to keep only the fragments that passed MAPQ30 or alternatively produce a fragment file from atac.bam.MAPQ30.

Thanks for your help.

**Comment by wbaopaul** [comment]
Just notice this issue, the fragments files was indeed produced from MAPQ30 bam file.
