### ISSUE TITLE
Input fastqs not from 10x Genomics

### ISSUE THREAD

**Issue by sebboegel** [wbaopaul/scATAC-pro#44]
Hi,

i have sc ATAC seq data, which is not produced by 10x Chromium. After bcl2fastq, i have R1.fastq, R2.fastq (forward and reverse) and I1 und I2 fastq. I would love to start the pipeline with demux_fastq, however i realized that is designed for 10x with R1,3 and R2. Any recommendations how to adapt the input files?

Thank you very much

Sebastian

**Comment by wbaopaul** [comment]
Hi, 
can you let me  know more about the I1 and I2 fastq (such as what information are provided), are cell barcodes written in them corresponding to R1 and R2 fastqs?  A snapshot of few lines of those fastq files are super helpful. 

Wenbao

**Comment by sebboegel** [comment]
Dear Wenbao,

thank you very much for your fast reply. We have sc ATAC seq data from mice. We used ICELL 8 system from Takara and sequenced 900 cells (with 4 different conditions) on MiSeq. We used different combnations for i5 und i7 indices (see attached samplesheet).
<img width="1002" alt="samplesheet" src="https://user-images.githubusercontent.com/7408050/118607346-c01e2a80-b7b8-11eb-8e34-55fa5436975f.png">.
After bcl2fastq i get one r1 and one R2.fastq file (for reverse and forward reads). I1 contains index 1 for each read in R1 and I2 contains index 2 for each read in R2:

![Bildschirmfoto 2021-05-18 um 09 32 20](https://user-images.githubusercontent.com/7408050/118610379-fe691900-b7bb-11eb-8f5d-9f75ee23aea9.png)

So, i thought to skip the demux step with your software and performed demuxing with th software provided by Takara, which gives me R1 and R2.fastq
![Bildschirmfoto 2021-05-18 um 09 35 07](https://user-images.githubusercontent.com/7408050/118610729-5b64cf00-b7bc-11eb-95c7-0594f192e733.png)

Using these 2 files as input (starting with mapping) does not produce a matrix file and the 4th column of fragments.tsv does not contain any barcode. I guess the reason is, that the indices (barcodes) are not directly after "@" in the fastq header. Is that right? Could it be a workaround if i write a script changing the fastq header of my R1 and R2 fastq files, such that the indices are written directly after "@"?

Thank you very much for your help

Sebastian

**Comment by wbaopaul** [comment]
Thanks, if I understand correctly, you have two runs of barcodes with one added to R1 and the other to R2. Then you can run demplx_fastq  as follows:
`scATAC-pro -s demplx_fastq  -i your_R1_fastq_file,your_R2_fastq_file, your_index1_fastq_file, your_index2_fastq_file -c configure_use.txt `

Hope it helps,
Wenbao

**Comment by sebboegel** [comment]
Thanks a lot. The demux step worked properly. The mapping step produces a 3GB bam file, however an empty MAPQ30.bam file. But if i do "samtools view -h -b -q 30 output/mapping_result/atac.positionsort.bam -o output/mapping_result/test.mapq30.bam" i get an 2.2GB bam file.

The atac.positionsort.bam looks like:

![Bildschirmfoto 2021-05-19 um 08 21 07](https://user-images.githubusercontent.com/7408050/118765341-384d2480-b87b-11eb-845a-524efa2d3b61.png)


mapping.log file:

[main] Version: 0.7.17-r1188
[main] CMD: /usr/local/bin/bwa-0.7.17/bwa mem -t 13 /home/ubuntu/sravolume/mm10/mm10.fa output/demplxed_fastq/demplxed_Undetermined_S0_L001_R1_001.fastq.gz output/demplxed_fastq/demplxed_Undetermined_S0_L001_R1_001.fastq.gz
[main] Real time: 1383.336 sec; CPU: 17409.822 sec
BWA Mapping Done!
convert to bam ... 
Converting sam to bam ... 
Sorting bam file
[bam_sort_core] merging from 13 files and 13 in-memory blocks...
[bam_sort_core] merging from 13 files and 13 in-memory blocks...
Summarizing mapping stats ...
Simple mapping stats summary Done!
Getting txt file for read pair (fragment) information
Now I am starting to process read file: output/mapping_result/atac.positionsort.MAPQ30.bam .
...
I have read 0 reads from input read file: output/mapping_result/atac.positionsort.MAPQ30.bam .
Now I am writing the output to output/summary/atac.fragments.tsv .
It takes 0 seconds totally.
Output fragments is in the file output/summary/atac.fragments.tsv  . 
Fast sorting by R using data.table...
Warning message:
In fread(frags.file, header = F) :
  File 'output/summary/atac.fragments.tsv' has size 0. Returning a NULL data.table.
Error in setkeyv(x, cols, verbose = verbose, physical = physical) : 
  some columns are not in the data.table: V1,V2
Calls: setkey -> setkeyv
Execution halted
/home/ubuntu/scATAC-pro/scripts/Makefile:64: recipe for target 'mapping' failed
make: *** [mapping] Error 1

**Comment by wbaopaul** [comment]
One thing I can think about is that the memory you provided when running the mapping module may be too limited. Can you tell me how much memory you assign to your machine when running the mapping step? Usually it requires large memory (tens to hundreds Gb depending on your data size).  BTW, can you post your .MappingStat file under output/summary?  

In addition, I only see one run barcode in your bam file. Which scATAC-pro version are you using and can you snapshot few lines of your demultiplexed fastq file?

Thanks

**Comment by sebboegel** [comment]
@mapping: you were right.  I have 14 VCPUs and 32 GB RAM. In configure_user.txt i set -t 13. When i did -t 10 the mapping and MAPQ30 step worked properly.

@call_cell: everything runs smoothly, except the call_cell step, which produces an empty barcodes.txt (see call_cell.log):
Wed May 19 19:00:27 UTC 2021
Calling cell ...
FILTER is used for cell calling...
NULL

while the barcodes.txt in raw_matrix/MACS2 contains 588 barcodes:
![Bildschirmfoto 2021-05-20 um 10 26 25](https://user-images.githubusercontent.com/7408050/118945571-dc0b0300-b955-11eb-9001-56378d82b670.png)

So, i assume there might be an issue with the demultiplexing?
Here are some lines of the demuxed fastqs:
![Bildschirmfoto 2021-05-20 um 10 29 31](https://user-images.githubusercontent.com/7408050/118946024-4f147980-b956-11eb-89c1-47c15f340eb4.png)

I am using scATAC-pro version 1.3.0

@Mappingstats:
Total_Pairs    35417102
Total_Pairs_Mapped    35019444
Total_Uniq_Mapped    29956767
Total_Mito_Mapped    1180045
Total_Dups    8105842
Total_Pairs_MAPQ30    29160736
Total_Mito_MAPQ30    918451
Total_Dups_MAPQ30    6041704

**Comment by wbaopaul** [comment]
You can change the cutoffs in the configure_user.txt file for cell calling. The defaults are pretty stringent.

BTW, is the cell barcode expected? it seems only I1 barcode were written. Note that there should be no space around comma when specifying the input
 ` -i your_R1_fastq_file,your_R2_fastq_file,your_index1_fastq_file,your_index2_fastq_file `

Hope it helps.

**Comment by sebboegel** [comment]
Thanks for your reply. There is definetly something wrong with the barcodes. We have 2 indices and the combination of both is unique for each single cell. I need both to re-identify them later in the analysis.

When i perfom demuxing with the software provided by Takara (as we are using the icell8 system), i get the following R1 and R2.fastq
![118610729-5b64cf00-b7bc-11eb-95c7-0594f192e733](https://user-images.githubusercontent.com/7408050/119103061-05419700-ba1b-11eb-87a7-50eb3216a1fe.png)

However, using these 2 files as input (starting with mapping) does not produce a matrix file and the 4th column of fragments.tsv does not contain any barcode, but only numbers, e.g.

chr1	67517432	67517500	M05074	1
chr1	67517456	67517582	M05074	2
chr1	67517507	67517711	M05074	1
chr1	67517564	67517650	M05074	1
chr1	67517632	67517799	M05074	2
chr1	67517878	67517968	M05074	1
chr1	67518416	67518511	M05074	3
chr1	67518741	67518953	M05074	1
chr1	67519159	67519421	M05074	1
chr1	67519169	67519340	M05074	1
chr1	67519443	67519568	M05074	1
chr1	67519876	67520075	M05074	1
chr1	67520015	67520113	M05074	1
chr1	67520082	67520369	M05074	1
chr1	67520210	67520293	M05074	1
chr1	67520284	67520401	M05074	1
chr1	67520340	67520494	M05074	2

Error in get_mtx:

Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: sparseMatrix -> <Anonymous>
Execution halted
/home/ubuntu/scATAC-pro/scripts/Makefile:130: recipe for target 'get_mtx' failed
make: *** [get_mtx] Error 1

MappingStats:
Total_Pairs    34468904
Total_Pairs_Mapped    34308587
Total_Uniq_Mapped    29352426
Total_Mito_Mapped    1157713
Total_Dups    7845048
Total_Pairs_MAPQ30    28573551
Total_Mito_MAPQ30    901644
Total_Dups_MAPQ30    5841530

**Comment by wbaopaul** [comment]
The format of demultiplexed fastq file by Takara software is not compatible with scATAC-pro.  If run the demplx_fastq of scATAC-pro correctly, the expected demultiplexed fastq file should be with read name like this:
@index2Barcode_index1Barcode:Your_Original_read_name. 

Can you tell me how did you run the` demplx_fastq` module and any abnormal message printed in output/logs/demplx_fastq.log?

Thanks

**Comment by wbaopaul** [comment]
I found and corrected a minor bug for `demplx_fastq`, and now it works for two or more index files. Please try the latest commit/version @sebboegel .

Thanks.

**Comment by sebboegel** [comment]
Thank you very much. This seemed to work. the demuxed fastq files are now in the right format. I was able to run until rmDoplets (with changes to the parameters in call cell) successfully. 

I will now proceed and get back with issues if they occur.

Thanks a lot again for your valuable  help.
