### ISSUE TITLE
cell calling

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#45]
Hi,

I have a few questions pertaining to the cellranger cell calling algorithm that atac-pro provides. 
Could you please explain exactly which version of cellranger does atac-pro cellranger script follow (since 10x made several changes to their cell calling methods for scATAC)? Also, is it excatly the same as that version of cellranger or are there expected to be minor changes?

In addition, since I did not understand this from your paper, could you please provide an overview of how this cellranger script calls the cells (is it the knee-point approach?) and if it can be advantageous over customized/emptydrop method? 

Finally, have you used any methods to detect barcode doublets?

Thank you so much for all your support.

**Comment by wbaopaul** [comment]
To me, there is no way to exactly implement cellranger cell calling algorithm since the algorithm was only briefly descriped on 10x genomics website. I essentially implemented it with some I would say minor modifications:
1) no doublets/multiplets calling step
2) Two component NB mixture model was fitted but the cells were not called based on knee-point, instead, I used posterior probility: barcodes with posterior probility  from the comonent with larger mean = 1 are called cells, otherwise non-cell. Even the cutoff here seems stringent, there always be many cells identified.

I basically only recommend customized method based on single cell QC according to my experience, because it's simple and easy to interpretate, and the other two methods highly depend on some model assumption, which is hard to validate and may not work for some data.

A new module called `rmDoublets` for removing potential doublets will be added for the next scATAC-pro release (will be v1.3.1) in few days.

Hope it helps,
Best

**Comment by AnjaliC4** [comment]
Thanks so much for this information. I am having a hard time figuring out a standardized way to call cells using customized filtering. Since it varies based on library complexity. Do you recommend any methods that you tested/others to standardize  the cut-offs for cell filtering for all the libraries?  
In addition,the cut-offs you used in the paper, seem very high for my data - so how do you recommend standardizing this?

Looking forward to rmDoublets, thats very exciting!

**Comment by wbaopaul** [comment]
The cutoffs used for original paper are indeed very stringent and you may need to adjust them for some of your data. Usually I and my labmates relaxed  total unique fragments to 3000, the min frac_in_peak to 0.25, and the fraction of mitchondrial reads less than 10 (or 20% for some data).  You can also check the plot of the frac_in_peak vs the total number of unique fragments per cell in the html report. If there is a clear separated group of barcodes on ther upper-right quadrant, those barcodes are more likely to be cells.  But in short, I have no way to standardize those cutoffs.

Hope it helps.

**Comment by wbaopaul** [comment]
The aforementioned `rmDoublets` module was added in v1.3.1.

**Comment by AnjaliC4** [comment]
Hi Wenbao,

This is a bit of an extra request. There is a new tool for ATAC doublet remover: 
 https://github.com/UcarLab/ATAC-DoubletDetector 

It is based on read counts, so may be more appropriate for ATAC than doublet finder (in my opinion).  Would it be please possible for you to add this to scATAC-pro pipeline? They need a singlecell.csv format which scATAC-pro does not generate. One could add a column in qc_per_barcode file with --isCellid to make it compatible, please see this issue - https://github.com/UcarLab/ATAC-DoubletDetector/issues/6

Please let me know if this may be easy to implement.

Thank you,
Anjali

**Comment by wbaopaul** [comment]
@AnjaliC4  Thanks for the suggestion! I would wait until that work be published and people really like it better than DoubletFinder.

**Comment by AnjaliC4** [comment]
Hi Wenbao,

I understand. That's alright. 

I have more questions related to FILTER cell calling. Does the --min-unique-fragments and --max-fragments thresholds in FILTER cell calling calculated based on a minimum number of unique fragments overlapping peaks per cell? Or is this independent of peak calling? 

In addition, I have seen that median fragments per cell calculated in QC report are higher when using BIN rather than MACS2 - what do you think maybe a reason for that? Is binning a better approach in your experience?

I also want to thank you for making this open-source pipeline - it really allows one to play with multiple parameters. :)

**Comment by wbaopaul** [comment]
Thanks for using scATAC-pro.

The min-unique-fragments and max-uniqeu-fragments parameters are independent of peak calling.

The cells are called differently (therefore different median fragments per cell) if you use BIN other than MACS2. Note that in the former case, each BIN is like a "peak". All barcodes may have very high fraction of fragments in 'peaks'.  In latter case, a barcode with high number of fragments could have a very low fraction of fragments in peaks and will not be treated as a cell barcode., similarly, a barcode with low number of fragmetns could have a high fraction of fragments in peaks and will be treated as a cell barcode. So, it's possible that MACS2 option result in cells with lower median fragmetns per cell, but it doesn't mean it's worse.

Hope this helps,

**Comment by AnjaliC4** [comment]
Hi Wenbao,

I understand that min-unique-fragments and max-uniqeu-fragments parameters for cell calling in configure script are independent of peak calling. Is min/max-uniq frag same as total_frags in seurat_obj?
I was also wondering how the raw_matrix is called? From what I could understand is that barcodes < 5 reads are removed and some other processing - could you please explain the thresholds you have set for raw_matrix in the pipeline? Also, was barcodes called in raw_matrix dependent on peak calling or nCount_peaks? Thanks a lot!

**Comment by wbaopaul** [comment]
Yes, the min/max-uniq, and total frags are provided as metadata in the seurat_obj.  For raw matrix, there is only two filtering: remove barcodes with less than 5 reads; then remove peaks with less than 5 cells. This filtering is very less stringent.
Barcodes in raw_matrix do not dependent on peak calling or nCount_peaks. 
Hope it answered your questions.
