### ISSUE TITLE
Issue with executable file not found in $PATH

### ISSUE THREAD

**Issue by gaelcge** [wbaopaul/scATAC-pro#47]
Hi
Not sure what I am doing wrong so I am asking for help.
I have pull the singularity sif file on our hpc cluster but I got :
FATAL:   " ": executable file not found in $PATH.

I am using singularity 3.6 from /opt/software/singularity-3.6/bin/singularity
Here is the sif file as seen with singularity sif header scatac-pro_latest.sif
Launch:   #!/usr/bin/env run-singularity
Magic:    SIF_MAGIC
Version:  01
Arch:     amd64
ID:       8d6d707d-e1df-482e-a836-0abde829829d
Ctime:    2021-07-12 14:41:02 +0000 UTC
Mtime:    2021-07-12 14:41:02 +0000 UTC
Dfree:    45
Dtotal:   48
Descoff:  4096
Descrlen: 27KB
Dataoff:  32768
Datalen:  5GB

Thanks for your help.

**Comment by wbaopaul** [comment]
Can you post the full command you have used and the full error message? Thanks.

**Comment by gaelcge** [comment]
Thanks
This is the command to pull the container = 

singularity pull -F docker://wbaopaul/scatac-pro:latest 

WARN[0000] "/run/user/3045930" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/3045930: no such file or directory: Trying to pull image in the event that it is a public image. 
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
WARN[0001] "/run/user/3045930" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/3045930: no such file or directory: Trying to pull image in the event that it is a public image. 
WARN[0002] "/run/user/3045930" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/3045930: no such file or directory: Trying to pull image in the event that it is a public image. 
Getting image source signatures
Copying blob a4a2a29f9ba4 done  
....
Writing manifest to image destination
Storing signatures
2021/07/12 07:32:10  info unpack layer: sha256:a4a2a29f9ba48efd3d2075f395538b2eec56fb1bedfb7aecf5e54174446f9e2a
...
2021/07/12 07:35:20  warn rootless{usr/local/bin/bedops/bin/bam2bed} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
...
INFO:    Creating SIF file...

ls -la
5453565952 Jul 12 07:41 scatac-pro_latest.sif

#Then here the exec command = 

singularity exec --bind $HOME --cleanenv -H $workingpath $SCRATCH/scatac-pro_latest.sif \
scATAC-pro -s demplx_fastq \
-i $fastqpath/pe1_fastq.gz,$fastqpath/pe2_fastq.gz,$fastqpath/index_fastq.gz \
-c $workingpath/configure_user.txt

#the error message was coming after singularity exec =
FATAL:   " ": executable file not found in $PATH
#then
bash: scATAC-pro: command not found

I had the same issue when pulling the sif file into my project directory (in case it was due to having pull the sif file into scratch)
Thanks
Gael

**Comment by wbaopaul** [comment]
I think some of your bash varibles may not exist that caused the error. Can you double check any typo for the values of those variables or you may use the full path instead of those variable?  Or, some time $fastqpath/pe1_fastq.gz should be wrote as ${fastqpath}/pe1_fastq.gz to aviad potential issues.

Hope it helps. Thanks.

**Comment by wbaopaul** [comment]
Close this issue since it's inactive for more than 3 months
