### ISSUE TITLE
installation error: value too great for base (error token is "10#line")

### ISSUE THREAD

**Issue by leonvgurp** [wbaopaul/scATAC-pro#48]
Hi,

working on mac osx 10.15.7 (catalina), on a virtual python environment (python 3.9.6). Downloaded the latest git clone, enter the directory and try to configure the installation using `make configure prefix=/Users/vangurp/scATAC-pro`. macs2 is installed, then get errors. Full output:

```
Starting scATAC-pro installation ...
Dependencies will be install in /Users/vangurp/scATAC-pro
 macs2 not detected, trying to install it now ...
Requirement already satisfied: macs2 in /Users/vangurp/Library/Python/3.9/lib/python/site-packages (2.2.7.1)
Requirement already satisfied: numpy>=>=1.17 in /Users/vangurp/python3env/lib/python3.9/site-packages (from macs2) (1.21.0)
usage: dirname path
/Users/vangurp/scATAC-pro/scripts/install/install_dependencies.sh: line 83: 10#line: value too great for base (error token is "10#line")
/Users/vangurp/scATAC-pro/scripts/install/install_dependencies.sh: line 87: 10#line: value too great for base (error token is "10#line")
macs2 v2.2.5 or higher is needed [ detected].
make[1]: *** [configure] Error 1
make: *** [configure] Error 2
```

Please advise how to continue? Many thanks in advance!

**Comment by wbaopaul** [comment]
Hi, thanks for trying scATAC-pro. Seems there is some issue in installing macs2. can you check `which macs2` or manually re-install macs by pip?

BTW, I generally not recommend  use scATAC-pro on mac pc (except you have a machine with a big memory because many module of scATAC-pro requires large memory, especially the mapping module.)

Thanks,

**Comment by wbaopaul** [comment]
close this issue since it's inactive for more than 3 months
