### ISSUE TITLE
Empty fragments.txt file @10xconvertbam 

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#5]
Hi,

I tried converting 10x cellranger generated positionsorted.bam file into scATACpro.positionsorted.bam, which works, however the summary folder has an empty fragment.txt file. Mappingstats file looks fine. Please let me know if you have any ideas on how to fix this. The log file generated: 
Aligning ...
write the barcode in format of scATAC-pro:
Summarizing mapping stats ...
Simple mapping stats summary Done!
Getting txt file for read pair (fragment) information
Out of memory!
Now I am starting to process read file: /home/scratch/10xbam/mapping_r$
...
make: *** [/home/scATAC-pro/scripts/Makefile:92: convert10xbam] Error 1

**Comment by wbaopaul** [comment]
I have tested this module using a small 10x pbmc 5k bam file. I guess the error you got may arise from lack of memory, in your log file, there is "Out of memory " issue. Can you increase the memory and do this module again? Hope it helps.

Wenbao

**Comment by AnjaliC4** [comment]
I resolved this. Thank you.
