### ISSUE TITLE
Question: why MACS2 is forced to run SE mapping?

### ISSUE THREAD

**Issue by Puriney** [wbaopaul/scATAC-pro#50]
https://github.com/wbaopaul/scATAC-pro/blob/b6380d961bd0aae9da1ff0acea7f95e8138c43f1/scripts/call_peak.sh#L28

Hello, I have 3 questions.

1. How can I let MACS2 to run in the PE mode because my input sequencing reads are pair-end? 

I thought the parameter in the config file can set this process. But I did not see it used here. 

```
isSingleEnd = FALSE 
```

2. Is there any particular reason scATAC-pro force MACS2 to run in single-end mode?

3. How the above `isSingleEnd` parameter affect the entire process? Where is it used?

Many thank.

**Comment by wbaopaul** [comment]
Thanks.This is a bug. I just pushed a fix for this issue to branch v1.4.1, it will automatically use BAMPE if isSingleEnd=FALSE and BAM otherwise. Pleas use branch v1.4.1. (I will merge the updates to master branch soon).
isSingleEnd is mostly used in the *dex_fastq* and  *trimming* module.
