### ISSUE TITLE
Single-end reads

### ISSUE THREAD

**Issue by max3rd** [wbaopaul/scATAC-pro#52]
Hi,
We cannot use the pipeline when using the single-end fastq file as input. We can run the pipeline with no problem with the module (demplx_fastq, trimming). However, when we used the mapping module, the pipeline assumes the reads to be paired-end reads thus cannot proceed. 

## filtering low quality and/or deplicates for downstreame analysis
${SAMTOOLS_PATH}/samtools view **-f 0x2** -b -h -q 30 -@ $ncore ${mapRes_dir}/${OUTPUT_PREFIX}.positionsort.bam -o ${mapRes_dir}/${OUTPUT_PREFIX}.positionsort.MAPQ30.bam 
${SAMTOOLS_PATH}/samtools index -@ $ncore ${mapRes_dir}/${OUTPUT_PREFIX}.positionsort.MAPQ30.bam 

if [ $MAPQ -ne 30 ]; then
     ${SAMTOOLS_PATH}/samtools view **-f 0x2** -b -h -q $MAPQ -@ $ncore ${mapRes_dir}/${OUTPUT_PREFIX}.positionsort.bam -o ${mapRes_dir}/${OUTPUT_PREFIX}.positionsort.MAPQ${MAPQ}.bam 
fi

When we manually remove the -f 0x2 option, the following Perl script (simply_bam2frags.pl) still assumes the paired-end read.
Can you please let us know how to run the pipeline with single-end fastq files?

PS, we did specify isSingleEnd = TRUE.

Thank you

**Comment by wbaopaul** [comment]
Thanks for reporting this issue. I have added a correction in the dev branch. Can you give it a try and let me know if there is still  a problem? Thanks.

**Comment by max3rd** [comment]
Thanks for the quick response, we tested the scripts in the dev branch and it works for mapping. However, when we proceed for peak calling, the MACS2 seems forced to call peak with paired-end reads. Again, we did specify isSingleEnd = TRUE.
We do see the codes below in the call_peak.sh script, but the MACS2 keeps using BAMPE as input:
		if [ ${isSingleEnd} = 'TRUE' ]; then
			${MACS2_PATH}/macs2 callpeak -t $input_bam --outdir $work_dir -n $out_prefix -f BAM $MACS2_OPTS 
		fi
		
		if [ ${isSingleEnd} = 'FALSE' ]; then
			${MACS2_PATH}/macs2 callpeak -t $input_bam --outdir $work_dir -n $out_prefix -f BAMPE $MACS2_OPTS 
		fi

**Comment by wbaopaul** [comment]
That's weird. I have tested the call_peak module works OK with a single-end .bam file as input. Can you let me know more detail of the error message or how did you run it?

**Comment by max3rd** [comment]
**The code we used for singularity:**
singularity run scatac-pro_latest.sif scATAC-pro -s call_peak  -i /fastscratch/pbmc10k.positionsort.MAPQ30.bam -c /fastscratch/configure_user.txt 

**The setting in configure_user.txt**
######################################################################
global setting 
######################################################################
OUTPUT_PREFIX = pbmc10k     ## prefix for ouput file name
isSingleEnd = TRUE         ## scTHS-seq uses single end sequencing

**The output from peak.xls**
This file is generated by MACS version 2.2.7.1
Command line: callpeak -t /fastscratch/pbmc10k.positionsort.MAPQ30.bam --outdir output/peaks/MACS2 -n pbmc10k -f BAMPE -q 0.05 -g hs --nomodel --extsize 200 --shift -100
ARGUMENTS LIST:
name = pbmc10k
format = BAMPE
ChIP-seq file = ['/fastscratch/pbmc10k.positionsort.MAPQ30.bam']
control file = None
effective genome size = 2.70e+09
band width = 300
model fold = [5, 50]
qvalue cutoff = 5.00e-02
The maximum gap between significant sites is assigned as the read length/tag size.
The minimum length of peaks is assigned as the predicted fragment length "d".
Larger dataset will be scaled towards smaller dataset.
Range for calculating regional lambda is: 10000 bps
Broad region calling is off
Paired-End mode is on

**Comment by wbaopaul** [comment]
Are you using scATAC-pro v1.4.1 from signularity (the log file will tell which scATAC-pro version you are running)? If you are indeed using v1.4.1 and the problem is still there, I am not sure the reason and will look into it, and probably you can install and try the dev branch directly since you already tested the updated script?

**Comment by max3rd** [comment]
bamPE="BAM"
    if [[ "$isSingleEnd"="FALSE"  ]]; then
        bamPE="BAMPE"
    fi
        ${MACS2_PATH}/macs2 callpeak -t $input_bam --outdir $work_dir -n $out_prefix -f $bamPE $MACS2_OPTS

This is the source code of call_peak.sh what we found in our 1.4.1 singularity image.

**Comment by wbaopaul** [comment]
Just realized that the singularity version was a little behind the github v1.4.1. I have updated the docker image to the latest of scATAC-pro. Please download and give it a try!

**Comment by max3rd** [comment]
It works out with the latest docker image (v1.4.2). Thank you for your help.
