### ISSUE TITLE
Program not recognizing parameters

### ISSUE THREAD

**Issue by HuringdaCat** [wbaopaul/scATAC-pro#53]
Hi, I just installed scATAC-pro and am trying to get it running. But it seems it's not recognizing any parameters or arguments I passes in the command line, but just always gives back the following instructions without any errors. I cannot figure out whether there's something wrong with the way I give the parameters. Could you please advice what's possibly causing the issue?

![image](https://user-images.githubusercontent.com/41116805/155466425-6e1b2177-59b2-4f3a-8959-08e0ab0d89ce.png)

**Comment by wbaopaul** [comment]
Hi, I observed several issues:
1) there should be no space after the comma between the two fastq files.
2) scATAC-pro doesn't take output file name, instead just takes the output directory. (say you specify -o BC_2/, then the alignment results will be saved under BC_2/mapping_result/, similar for other steps). There is OUTPUT_PREFIX parameter in the configure_user.txt file, which will be used as prefix to the name of each output file.
3)(optional, if you didn't know it) if you are using 10x data, you can do all processing steps in one command, something like
 
```
scATAC-pro -s process -i 10x_fastq_folder -c configure_user.txt -o output
```
Hope it helps!

**Comment by HuringdaCat** [comment]
Hi,
Directly giving the 10X fastq folder is super helpful and it works well! Thanks a lot!

Best
Zhiyun
