### ISSUE TITLE
demultiplexing taking way too much time!

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#54]
Hi, 

Is there a way to make demultiplexing procedure any faster? Even with 32 cpus and 200g mem - it takes 2 days to finish for a 30g fastq files. If you could please implement a faster version somehow - or suggest ways for it - that will be a huge time saver!

Thanks

**Comment by wbaopaul** [comment]
Thanks for pointing it out and we will try to improve it for future release. The demultiplexing step is slow but not to that extend as you mentioned(should be also relate to your computers). In my side, fastq files with 30G typically can be done within 10hrs.
