### ISSUE TITLE
Fatal error when running scATAC-pro 1.5

### ISSUE THREAD

**Issue by aseyedia** [wbaopaul/scATAC-pro#55]
Hi Wenbao,

I am trying to run scATAC-pro 1.5.0 on some example data in the same fashion that I was able to successfully use scATAC-pro 1.4.4 (through singularity), and I am unfortunately running into the following error:

```shell
(base) [seyediana@g-2-01 standard-pipeline-w-footprint]$ singularity exec \
>   --bind /mnt/isilon/ \
>   --cleanenv -H /mnt/isilon/cscb/atac/cscb-scATACseq-pipeline/ \
>   /mnt/isilon/cscb/atac/scATAC-pro_1.5.0/scatac-pro_1.5.0.sif \
>     scATAC-pro --step process \
>       -i ../atac_pbmc_1k_nextgem_fastqs \
>       -c configure_user.txt --verbose
FATAL:   "scATAC-pro": executable file not found in $PATH
```

I am resorting to building the GitHub repo right now, and hopefully that proceeds without any issues. I will keep you posted if anything arises.

**Comment by wbaopaul** [comment]
Thanks for pointing this out. I forgot to update the $PATH in singularity version. Just update it. Please re-pull it and give it a try! Thanks.

**Comment by aseyedia** [comment]
Works now. Thanks!
