### ISSUE TITLE
Annotations for different genomes

### ISSUE THREAD

**Issue by Gunjan-Dixit** [wbaopaul/scATAC-pro#56]
Hi,
Can you advise how to generate or where to download the annotations for Drosophila (dm6) genome-
Eg. dm6_promoters.bed and dm6.enhancers.bed

Thank you.

Regards,
Gunjan

**Comment by wbaopaul** [comment]
I am not sure but maybe you can check out in this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6203779/
If you are not specifically interested in the % of reads mapped to promoter or enhancer, you can skip this by running scATAC-pro (with a fake .bed file for each of these annotation files). Hope this helps!
