### ISSUE TITLE
No mapping results

### ISSUE THREAD

**Issue by Larrycpan** [wbaopaul/scATAC-pro#57]
I perform `scATAC-pro -s process -i fastq1.gz,fastq.gz,barcode.fastq.gz -c configure_user.txt`, and trimmed.demplxed.PE1/2.fastq.gz is correctly obtained. However, the process is terminated at the mapping procedure, and no mapping results are shown. How to fix it?

**Comment by wbaopaul** [comment]
Can you check the log file for any warning or error? Also, check anything abnormal in your trimmed fastq files. Usually, it needs large memory for the mapping step (at least 100G, also depends on the data size), make sure you specify enough memory.
