### ISSUE TITLE
Bowtie2 seemed not installed in the singularity

### ISSUE THREAD

**Issue by Puriney** [wbaopaul/scATAC-pro#60]
Hello Wenbao, 
I am using `scATAC-pro -s mapping` via your singularity. I found it will show the following error when I used the bowtie2 aligner. 

```
Aligning ...
Starting bowtie2 alignment ...
/usr/local/bin/scATAC-pro_1.5.0/scripts/mapping_bowtie2.sh: line 19: /bowtie2: No such file or directory
Bowtie2 Mapping Done!
```

I have two successful runs: 
- If I use BWA as specified in the user config file, the same command with the same data successfully works. 
- I installed the version 1.4.1 locally. The mapping by bowtie2 works because bowtie2 is usable and recognized by scATAC-pro. 

Therefore, I was wondering if the global variable`${BOWTIE2_PATH}` is not set in your singularity.  Or bowtie2 is not installed. Or the path to bowtie2 is not properly set in the singularity. See https://github.com/wbaopaul/scATAC-pro/blob/4564c508205996e189ab8c4c65d9b2b928da6ae3/scripts/mapping_bowtie2.sh#L19

The scATAC-pro version I pulled from your singularity is 1.5.0.

**Comment by Puriney** [comment]
Related issue #57

**Comment by wbaopaul** [comment]
Thanks @Puriney for pointing this out. Bowtie2 was indeed missed in the singularity version. I have just installed it for the singularity version and please feel free to pull the image and run it. Thanks!

**Comment by Puriney** [comment]
I am pulling it now. But this time it is very strange that it showed `"INFO:    Creating SIF file..."` and then stayed here forever without generating the sif file. 

I will leave the issue open for now as I am testing on a different machine and a different user account.

**Comment by wbaopaul** [comment]
Works at my side. Maybe put the pulling script in a HPC job helps.

**Comment by Puriney** [comment]
I still cannot pull it so I will use bwa instead.
