### ISSUE TITLE
Error in mapping with bwa

### ISSUE THREAD

**Issue by edfajardo** [wbaopaul/scATAC-pro#63]
Hi.  I am running scATAC-pro_1.5.1 from the command line.  I had done the demultiplexing step before so I started from trimming (i.e., -s process_no_dex).  The trimming step finished successfully but the mapping step failed immediately, without giving a helpful message in the log, just the standard error of bwa saying giving the right format for the command (but the actual command issued internally was not printed).  After looking at the scripts, I discovered the error:

Line 44 of script mapping_bwa.sh (for paired-end and the corresponding for single-end, line 42) reads:

`${BWA_PATH}/bwa mem $BWA_INDEX $BWA_OPTS ${fastqs[0]} ${fastqs[1]}  > ${mapRes_dir}/${OUTPUT_PREFIX}.sam
`

That is incorrect because the options should go before the index file name.  After changing the order of the parameters, as seen in the following line, the mapping step is proceeding right now:

`${BWA_PATH}/bwa mem $BWA_OPTS $BWA_INDEX ${fastqs[0]} ${fastqs[1]}  > ${mapRes_dir}/${OUTPUT_PREFIX}.sam`

Just wanted to let you know.  

If anyone finds this issue and wants to fix it, the script that has to be changed is in the scATAC-pro_1.5.1/scripts/ directory within the install directory (that is, NOT in the scripts directory that you also see in the downloaded scATAC-pro directory; you have to go into scATAC-pro_1.5.1, which is created after installation inside the downloaded scATAC-pro). 

Eduardo

**Comment by wbaopaul** [comment]
Thanks for pointing this out. It's interesting that the order of INDEX and OPTs matters in your side since it hasn't been an issue for many users include me. I will re-order them anyway in next update. BTW, do you mind telling which exact OPTs are you using? Because I haven't tested other options except the number of threads.

**Comment by edfajardo** [comment]
I have not used any other options.  This is was the first time running scATAC-pro so I went pretty much with the defaults.  I don't use bwa regularly so I can't really say much about the order of the parameters, beyond what I get then I run bwa mem with no parameters: 

Usage: bwa mem [options] <idxbase> <in1.fq> [in2.fq]

I do have one simple suggestion (which I implemented on my installation): add an echo statement to mapping_bwa.sh right before running the bwa command to print out the exact command that is being issued (the new line would become line 44 and the command would be on line 45).  That facilitates troubleshooting because the log file will show the exact command that was passed to the computer.

Thank you for your prompt reply. 

Eduardo

**Comment by wbaopaul** [comment]
Thanks for your suggestion. Actually, if the mapping step was run correctly, the command line will be automatically written in the log file (under output/logs/mapping.log or process.log if you run the wrapped module), as part of running message from bwa mem.

**Comment by edfajardo** [comment]
Hi again, 

Looks like there is an error in line 31 of the generate_signal.sh script, when calling bamCoverage to generate a bedgraph file.  It reads:

`  --bam $input_bam --binSize 20 --skipNonCoveredRegions -- --normalizeUsing BPM \ `

There is an extra set of double dashes indicating that a switch is following, but instead it is followed by blank.  It causes an error, reporting the following in the aggr_signal.log file:

`usage: An example usage is:$ bamCoverage -b reads.bam -o coverage.bw
bamCoverage: error: the following arguments are required: --outFileName/-o
`

The line should read:

` --bam $input_bam --binSize 20 --skipNonCoveredRegions --normalizeUsing BPM \`

After the correction, the script runs without errors.  

Thanks. 

Eduardo

**Comment by wbaopaul** [comment]
Thanks again. Both were correctted!
