### ISSUE TITLE
analyze species neither human nor mouse

### ISSUE THREAD

**Issue by tao-bioinfo** [wbaopaul/scATAC-pro#7]
I see that R modules such as `BSgenome.Hsapiens.UCSC.hg38` has been listed. They must be related with gene annotations in this pipeline.

Now I am dealing with species that is neither human nor mouse, and I've already have a custom built R package called `BSgenome.foo.custom.bar`. What should I need to modify the source code to run them?

**Comment by wbaopaul** [comment]
That's a good question. I guess only the motif analysis module needed to be changed:
YOUR_INSTALL_PATH/scATAC-pro1.1.0/scripts/src/motif_analysis.R, you can add following two lines at line 27 like:
library(BSgenome.foo.custom.bar)
genoName='BSgenome.foo.custom.bar'

Thanks

Wenbao
