### ISSUE TITLE
peak calling macs2 for c. elegans

### ISSUE THREAD

**Issue by lengfei5** [wbaopaul/scATAC-pro#8]
Hi, 

Thank you for such a flexible and nice processing pipeline.
I went though the source code and found that the peak calling, macs2, the organism parameter is only for human and mouse. 
So I am wondering if possible to put this parameter for macs2 into configuration_user file.
Perhaps together with macs other parameters, e.g. --nomodel --extsize 147, 
because macs2 complained without those parameters. 

Thanks.

**Comment by lengfei5** [comment]
I realized that people can easily add more parameters for macs2 in configuration_user file.
Then please ignore then extra pamameters, eg. --nomodel --extsize 147.
Please only move the organism parameter into the configuration_user.

**Comment by wbaopaul** [comment]
Good point! I just updated it as you suggested, thanks.

Wenbao
